(function() {
  const lang = localStorage.getItem('sci-lab-lang') || 'ko';
  if (lang !== 'en') return;

  const dictionary = {
    // Common terms
    "뒤로": "Back",
    "제어 패널": "Control Panel",
    "원리 설명": "Theory Guide",
    "접기 ✕": "Fold ✕",
    "열기 ☰": "Open ☰",
    "▶ 재생": "▶ Play",
    "⏸ 일시정지": "⏸ Pause",
    "초기화": "Reset",
    "물체 1": "Object 1",
    "물체 2": "Object 2",
    "총합": "Total",

    // Physics
    "역학 및 운동 법칙 시뮬레이션": "Mechanics & Laws of Motion Simulation",
    "역학 및 운동 법칙": "Mechanics & Laws of Motion",
    "힘과 가속도 (F=ma)": "Force & Acceleration (F=ma)",
    "운동량 보존과 충돌": "Momentum & Collision",
    "물리 시뮬레이션 학습 가이드": "Physics Simulation Guide",
    "질량 (m):": "Mass (m):",
    "가하는 힘 (F):": "Applied Force (F):",
    "마찰 계수 (μ):": "Friction Coeff (μ):",
    "실시간 물리 데이터": "Real-time Physics Data",
    "가속도 (A)": "Acceleration (a)",
    "속도 (V)": "Velocity (v)",
    "마찰력 (F)": "Frictional Force (f)",
    "🔴 물체 1 (빨강)": "🔴 Object 1 (Red)",
    "🔵 물체 2 (파랑)": "🔵 Object 2 (Blue)",
    "질량 (m₁):": "Mass (m₁):",
    "초기 속도 (v₁):": "Initial Vel (v₁):",
    "질량 (m₂):": "Mass (m₂):",
    "초기 속도 (v₂):": "Initial Vel (v₂):",
    "운동량 (p = mv) [kg·m/s]": "Momentum (p = mv) [kg·m/s]",
    "운동에너지 (K = ½mv²) [J]": "Kinetic Energy (K = ½mv²) [J]",
    "가속도 (a):": "Acceleration (a):",
    "속도 (v):": "Velocity (v):",
    "마찰력 (f):": "Frictional Force (f):",
    "물체 1 질량 (m1):": "Mass 1 (m1):",
    "물체 1 초기 속도 (v1):": "Initial Vel 1 (v1):",
    "물체 2 질량 (m2):": "Mass 2 (m2):",
    "물체 2 초기 속도 (v2):": "Initial Vel 2 (v2):",
    "물체 1 속도 (v1):": "Velocity 1 (v1):",
    "물체 2 속도 (v2):": "Velocity 2 (v2):",
    "충돌 후 예상 속도 (v1', v2'):": "Expected Vel (v1', v2'):",
    "실시간 운동량 분석 (Momentum, p = mv)": "Real-time Momentum (p = mv)",
    "실시간 운동에너지 분석 (Kinetic Energy, K = 0.5mv²)": "Real-time Kinetic Energy (K = 0.5mv²)",
    "시뮬레이션을 재생하여 측정을 시작하세요": "Start simulation to measure data",
    "속도 및 가속도 실시간 추이 그래프 (F=ma)": "Real-time Velocity & Acceleration (F=ma)",
    "속도 (v)": "Velocity (v)",
    "가속도 (a)": "Acceleration (a)",
    "외력 F": "External Force F",
    "마찰력 f": "Frictional Force f",

    // Wave
    "파동의 간섭 시뮬레이션 (1D)": "Wave Interference Simulation (1D)",
    "파동의 간섭 시뮬레이션": "Wave Interference Simulation",
    "파동 중첩 원리 가이드": "Wave Superposition Guide",
    "1D 펄스 중첩 시뮬레이션 (A: 빨강, B: 파랑, 합성: 보라)": "1D Pulse Superposition (A: Red, B: Blue, Combined: Purple)",
    "🔴 펄스 A (우방향)": "🔴 Pulse A (Rightward)",
    "🔵 펄스 B (좌방향)": "🔵 Pulse B (Leftward)",
    "형태:": "Shape:",
    "가우스": "Gaussian",
    "삼각": "Triangle",
    "사각": "Square",
    "사인": "Sine",
    "진폭 (y_A)": "Amplitude (y_A)",
    "너비": "Width",
    "진폭 (y_B)": "Amplitude (y_B)",
    "시뮬레이션 조작": "Simulation Controls",
    "재생 속도:": "Simulation Speed:",
    "이동 속도": "Playback Speed",
    "◀ 이전": "◀ Prev",
    "다음 ▶": "Next ▶",
    "실시간 펄스 중첩 분석": "Real-time Pulse Superposition Analysis",
    "🔴 펄스 A 변위 (y_A)": "🔴 Pulse A Disp (y_A)",
    "🔵 펄스 B 변위 (y_B)": "🔵 Pulse B Disp (y_B)",
    "🟣 합성 변위 (y)": "🟣 Combined Disp (y)",
    "중첩 상태": "Superposition State",
    "보강 중첩 🟢": "Constructive 🟢",
    "상쇄 중첩 🔴": "Destructive 🔴",
    "교차 진행 중 ⚪": "Crossing ⚪",
    "분리되어 이동 중 ⚪": "Separating ⚪",
    "분리됨": "Separated",

    // Eclipse
    "태양계 식 현상 시뮬레이션": "Solar System Eclipse Simulation",
    "식 현상 시뮬레이션": "Eclipse Simulation",
    "일식 시뮬레이션": "Solar Eclipse Sim",
    "월식 시뮬레이션": "Lunar Eclipse Sim",
    "달 궤도 위치 (황경):": "Moon Orbit Pos:",
    "지구 공전 위치 (황경):": "Earth Orbit Pos:",
    "지구-달 거리 조절:": "Earth-Moon Distance:",
    "현상 종류": "Eclipse Type",
    "없음": "None",
    "일식 관측: 마우스 드래그로 우주를 회전해보세요. 달이 태양 앞에 정렬될 때 일식이 일어납니다.": "Solar Eclipse View: Drag to rotate the space. Solar eclipse occurs when Moon aligns with Sun.",
    "월식 관측: 마우스 드래그로 우주를 회전해보세요. 달이 지구의 본그림자/반그림자 영역에 들어갈 때 월식이 일어납니다.": "Lunar Eclipse View: Drag to rotate the space. Lunar eclipse occurs when Moon enters Earth's shadow.",
    "일식과 월식 시뮬레이션": "Solar & Lunar Eclipse Simulation",
    "일식/월식 기하학 가이드": "Eclipse Geometry Guide",
    "궤도 평면 설정": "Orbital Plane Settings",
    "달의 공전 궤도 경사각 (5.14°) 적용": "Apply Lunar Orbit Inclination (5.14°)",
    "황도면과 백도면 교차 (노드 형성)": "Ecliptic & Lunar Orbit Intersect (Nodes)",
    "천체 거리 배율 설정": "Celestial Distance Scaling",
    "실제 비례 (태양/지구/달 크기 및 궤도 거리)": "Real Scale (Sun/Earth/Moon Sizes & Orbits)",
    "학습용 축소 (천체 크기 강조 확대)": "Educational Scale (Exaggerated Sizes for Study)",
    "달의 위치 미세조정": "Fine-tune Moon Position",
    "일식 위치": "Solar Eclipse Pos",
    "월식 위치": "Lunar Eclipse Pos",
    "우주선 카메라 시점 설정": "Spaceship Camera View",
    "태양계 평면 시점 (Top-down)": "System Plain View (Top-down)",
    "지구 중심 시점 (Earth-centered)": "Earth-centered View",
    "월식/일식 관측 카메라": "Eclipse Observation Camera",
    "지구에서 본 낮/밤 지역 (태양광 조사)": "Day/Night Regions from Earth (Solar Illumination)",
    "달의 위상: 황도면 위치 기준": "Moon Phase: Based on Ecliptic Position",
    "천체 크기 배율:": "Celestial Size Scale:",
    "궤도 거리 배율:": "Orbital Distance Scale:",
    "지구 1년 주기:": "Earth 1-Year Cycle:",
    "달 1달 주기:": "Moon 1-Month Cycle:",
    "일식 관측 상태": "Solar Eclipse View",
    "월식 관측 상태": "Lunar Eclipse View",
    "우주 전체 투영 맵": "Universe Projection Map",
    "지구에서 본 낮/밤 및 태양 고도": "Day/Night & Sun Altitude from Earth",
    "개기 일식": "Total Solar Eclipse",
    "금환 일식": "Annular Solar Eclipse",
    "부분 일식": "Partial Solar Eclipse",
    "개기 월식": "Total Lunar Eclipse",
    "부분 월식": "Partial Lunar Eclipse",
    "반영 월식": "Penumbral Lunar Eclipse",
    "일반 진행": "Normal State",

    // Electrolysis
    "물의 전기분해 실험 시뮬레이션": "Water Electrolysis Simulation",
    "물의 전기분해 실험": "Water Electrolysis Experiment",
    "물의 전기분해 원리 가이드": "Water Electrolysis Guide",
    "물의 전기분해 (수소: (-)극 파랑도선, 산소/염소/요오드: (+)극 빨강도선)": "Water Electrolysis (Hydrogen: (-) Blue wire, Oxygen/Chlorine: (+) Red wire)",
    "실험 원리": "Theory Guide",
    "전원 장치 전압": "Power Supply Voltage",
    "전해질 농도 (": "Electrolyte Concentration (",
    "전해질 농도": "Electrolyte Concentration",
    "전해질 종류": "Electrolyte Type",
    "이온(Na+, OH-) 표시": "Show Ions (Na+, OH-)",
    "이온(Na+, Cl-) 표시": "Show Ions (Na+, Cl-)",
    "이온(H+, OH-) 표시": "Show Ions (H+, OH-)",
    "이온(Na+, OH-) 숨김": "Hide Ions (Na+, OH-)",
    "이온(Na+, Cl-) 숨김": "Hide Ions (Na+, Cl-)",
    "이온(H+, OH-) 숨김": "Hide Ions (H+, OH-)",
    "기체 확인 가상 실험 (기체 수집 완료 후 가능)": "Virtual Gas Test (Available after gas collection)",
    "🔥 (-)극 기체 확인 (성냥불)": "🔥 (-) Pole Gas Test (Match)",
    "🕯️ (+)극 기체 확인 (": "🕯️ (+) Pole Gas Test (",
    "실시간 전류 및 기체 포집량 분석": "Real-time Current & Gas Volume Analysis",
    "회로 총 저항": "Total Circuit Resistance",
    "회로 총저항": "Total Circuit Resistance",
    "흐르는 전류": "Current Flow",
    "기체 부피 비 (H₂ : O₂)": "Gas Volume Ratio (H₂ : O₂)",
    "분해 상태": "Decomposition Status",
    "반응 전": "Before Reaction",
    "화학 반응 가이드": "Chemical Reaction Guide",
    "전해질 용액 설정": "Electrolyte Solution Settings",
    "수산화나트륨": "Sodium Hydroxide (NaOH)",
    "염화나트륨": "Sodium Chloride (NaCl)",
    "순수한 물": "Pure Water (H₂O)",
    "전압 크기 (Power):": "Voltage (Power):",
    "이온 표시": "Display Ions",
    "미시적(분자) 관찰": "Microscopic View",
    "이온": "Ions",
    "표시": "Show",
    "숨김": "Hide",
    "가스 성분 검정 테스트": "Gas Test Tube Analysis",
    "(-)극 수소 가스": "(-) Pole Hydrogen Gas",
    "성냥 테스트": "Match Test",
    "(+)극 산소/염소 가스": "(+) Pole Oxygen/Chlorine Gas",
    "향불 테스트": "Splint Test",
    "리트머스 종이": "Litmus Paper",
    "실시간 전기화학 데이터": "Real-time Electrochemical Data",
    "기체 부피 비": "Gas Volume Ratio",
    "(-)극 수소 기체 (H₂)": "(-) Pole Hydrogen Gas (H₂)",
    "(+)극 산소 기체 (O₂)": "(+) Pole Oxygen Gas (O₂)",
    "(+)극 염소 기체 (Cl₂)": "(+) Pole Chlorine Gas (Cl₂)",
    "향불": "Wooden Splint",
    "전기분해 반응 중...": "Electrolysis in progress...",
    "(-)극 수소 확인 성냥 테스트 진행 중...": "(-) Pole Match Test in progress...",
    "(+)극 염소 기체 확인 리트머스 테스트 진행 중...": "(+) Pole Litmus Test in progress...",
    "(+)극 산소 기체 확인 향불 테스트 진행 중...": "(+) Pole Splint Test in progress...",
    "수소 기체 확인 완료 (폭발성 확인)": "Hydrogen gas verified (Explosive)",
    "염소 기체 확인 완료 (리트머스 종이 탈색)": "Chlorine gas verified (Litmus Bleached)",
    "산소 기체 확인 완료 (조연성 확인)": "Oxygen gas verified (Combustibility)",
    "전류 차단됨 (순수한 물)": "Current blocked (Pure Water)",
    "초기화됨 (반응 전)": "Reset (Before reaction)",
    "미시적 분자 반응": "Microscopic Molecular Reaction",
    "눈금": "Graduation",
    "수소": "Hydrogen",
    "산소": "Oxygen",
    "염소": "Chlorine",
    "H₂ (수소)": "H₂ (Hydrogen)",
    "O₂ (산소)": "O₂ (Oxygen)",
    "Cl₂ (염소)": "Cl₂ (Chlorine)",
    "POP! 퍽!": "POP!",
    "탈색! Bleached": "Bleached!",
    "활활! Rekindle": "Rekindle!",
    "이온(H⁺, OH⁻) 표시": "Show Ions (H⁺, OH⁻)",
    "이온(Na⁺, OH⁻) 표시": "Show Ions (Na⁺, OH⁻)",
    "이온(Na⁺, Cl⁻) 표시": "Show Ions (Na⁺, Cl⁻)",
    "이온(H⁺, OH⁻) 숨김": "Hide Ions (H⁺, OH⁻)",
    "이온(Na⁺, OH⁻) 숨김": "Hide Ions (Na⁺, OH⁻)",
    "이온(Na⁺, Cl⁻) 숨김": "Hide Ions (Na⁺, Cl⁻)",

    // Theory Guides - Physics
    "1. 힘과 가속도 (F = ma)": "1. Force and Acceleration (F = ma)",
    "뉴턴의 운동 제2법칙을 시각적으로 관측합니다. 질량(m), 가해지는 힘(F), 마찰계수(μ)를 직접 제어하며 물체의 실시간 가속도(a)와 속도(v) 변화 그래프를 비교해 보세요. 외력이 최대 정지 마찰력보다 작으면 물체가 움직이지 않는 물리 법칙이 적용되어 있습니다.": "Visually observe Newton's Second Law of Motion. Control mass (m), applied force (F), and friction coefficient (μ) directly, and compare the real-time acceleration (a) and velocity (v) graphs. If the external force is less than the maximum static friction, the object will not move.",
    "마찰 계수 (μ)와 마찰력:": "Friction Coefficient (μ) and Frictional Force:",
    "접촉 면의 거친 정도를 나타내는 수치로, 마찰 계수(μ)와 질량(m)이 클수록 운동을 방해하는 마찰력이 강해집니다. 시뮬레이션에서 마찰 계수를 계속 늘려도 마찰력이 증가하지 않는 이유는 두 가지입니다. 첫째, 물체가 움직이기 전(정정 상태)에 작용하는 마찰력은 가한 외력과 항상 같기 때문입니다. 둘째, 물체가 움직일 때의 최대 마찰력은 시뮬레이션의 물리적 한계를 고려하여 최대 50 N으로 제한되어 있기 때문입니다.": "A value indicating the roughness of the contact surface. The larger the friction coefficient (μ) and mass (m), the stronger the frictional force resisting motion. There are two reasons why frictional force doesn't increase indefinitely when you increase the coefficient in the simulation. First, before the object moves (static state), the frictional force is always equal to the applied external force. Second, when moving, the maximum frictional force is limited to 50 N considering the simulation's physical limits.",
    "2. 운동량 보존과 충돌 (Momentum)": "2. Momentum Conservation and Collision",
    "마찰이 없는 평면에서 두 물체의 탄성 충돌(e = 1.0)을 재현합니다. 질량과 초기 속도에 따라 충돌 전후의 개별 운동량(p)과 운동에너지(K)는 변화하지만, 계 전체의 총합은 보존되는 역학적 보존 법칙을 직접 수치와 실시간 바 게이지로 확인할 수 있습니다.": "Simulates elastic collision (e = 1.0) of two objects on a frictionless plane. Depending on mass and initial velocity, individual momentum (p) and kinetic energy (K) change before and after collision, but the total sum of the system is conserved. You can directly verify this conservation law with numbers and real-time bar gauges.",

    // Theory Guides - Wave
    "1. 중첩의 원리 (Superposition Principle)": "1. Superposition Principle",
    "서로 반대 방향으로 진행하는 두 파동 펄스가 어느 지점에서 겹칠 때, 합성파의 변위(y)는 각 파동이 단독으로 도달했을 때의 변위의 대수적 합인": "When two wave pulses traveling in opposite directions overlap, the combined wave's displacement (y) is the algebraic sum of the individual displacements, given by",
    "가 됩니다.": ".",
    "2. 보강 간섭 (Constructive Interference)": "2. Constructive Interference",
    "두 파동의 위상(방향)이 같아 마루와 마루가 만나거나 골과 골이 만나는 경우입니다. 두 변위의 방향이 같으므로 합성파의 진폭은 각각의 진폭의 합보다 커지게 됩니다.": "Occurs when waves are in phase, where crest meets crest or trough meets trough. Since the displacement directions are the same, the combined amplitude becomes greater than the sum of the individual amplitudes.",
    "3. 상쇄 간섭 (Destructive Interference)": "3. Destructive Interference",
    "두 파동의 위상이 서로 반대(마루와 골)로 만나는 경우입니다. 두 변위의 방향이 반대이므로 합성파의 진폭은 각각의 차이만큼 감소하고, 크기가 같으면 완전히 지워져 0이 됩니다.": "Occurs when waves are out of phase (crest meets trough). Since the displacements are opposite, the combined amplitude is reduced by their difference. If equal in size, they cancel each other completely to 0.",
    "4. 파동의 독립성": "4. Independence of Waves",
    "중첩을 마치고 서로 스쳐 지나간 파동은 다른 파동을 만나기 전과 마찬가지로 파형, 진폭, 속도, 진행 방향 등 본래의 고유한 특성을 아무런 변형 없이 그대로 유지하며 진행합니다.": "After overlapping and passing through each other, the waves continue with their original characteristics—shape, amplitude, speed, and direction—unaltered, just as before they met.",

    // Theory Guides - Electrolysis
    "1. 물의 전기분해란?": "1. What is Water Electrolysis?",
    "순수한 물은 전류가 잘 흐르지 않기 때문에, 전해질인 수산화나트륨($NaOH$)을 녹여 전류가 흐를 수 있도록 한 뒤 전기에너지를 가해 물을 수소 기체와 산소 기체로 분해하는 반응입니다.": "Since pure water does not conduct electricity well, an electrolyte like sodium hydroxide ($NaOH$) is dissolved to allow current flow, and electrical energy is applied to decompose water into hydrogen and oxygen gas.",
    "2. 각 전극에서의 화학 반응": "2. Chemical Reactions at Electrodes",
    "(-)극 (음극, Cathode): 환원 반응": "(-) Pole (Cathode): Reduction Reaction",
    "물 분자가 전자를 얻어 수소 기체($H_2$)와 수산화 이온($OH^-$)을 생성합니다.": "Water molecules gain electrons to produce hydrogen gas ($H_2$) and hydroxide ions ($OH^-$).",
    "(+)극 (양극, Anode): 산화 반응": "(+) Pole (Anode): Oxidation Reaction",
    "물 분자가 전자를 잃어 산소 기체($O_2$)와 수소 이온($H^+$)을 생성합니다.": "Water molecules lose electrons to produce oxygen gas ($O_2$) and hydrogen ions ($H^+$).",
    "3. 발생 물질의 부피 및 질량비": "3. Volume and Mass Ratio of Products",
    "전체 전하량 보존 법칙에 의해 이동하는 전자의 몰수가 동일하므로:": "Since the moles of transferred electrons are equal by the law of conservation of charge:",
    "-": "-",
    "물의 전기분해 (NaOH)": "Water Electrolysis (NaOH)",
    ": 수소와 산소가": ": Hydrogen and oxygen are produced in a",
    "부피비로 생성됩니다.": "volume ratio.",
    "염화나트륨(NaCl) 분해": "Sodium Chloride (NaCl) Electrolysis",
    ": 수소와 염소가": ": Hydrogen and chlorine are produced in an",
    "당량비로 생성됩니다.": "equivalent ratio.",
    "4. 전해질 종류별 양극(+) 생성물 및 검출법": "4. Anode (+) Products and Tests by Electrolyte",
    "수산화나트륨 ($NaOH$)": "Sodium Hydroxide ($NaOH$)",
    ": (+)극에서 산소 기체($O_2$)가 발생하며 향불을 대면 다시 활활 탑니다.": ": Oxygen gas ($O_2$) is produced at the (+) pole, which rekindles a glowing splint.",
    "염화나트륨 ($NaCl$)": "Sodium Chloride ($NaCl$)",
    ": (+)극에서 황록색 염소 기체($Cl_2$)가 발생하며 푸른 리트머스 종이를 빨갛게 물들였다가 탈색시킵니다.": ": Yellow-green chlorine gas ($Cl_2$) is produced at the (+) pole, turning blue litmus paper red and then bleaching it.",

    // Theory Guides - Eclipse
    "일식과 월식의 원리": "Principles of Eclipses",
    "1. 일식": "1. Solar Eclipse",
    "일식은 달이 태양과 지구 사이에 정확히 위치하여 태양 빛을 가리는 현상입니다. 달의 궤도는 타원형이기 때문에 지구와의 거리가 변하며, 이에 따라 일식의 종류가 달라집니다.": "A solar eclipse occurs when the Moon is positioned exactly between the Sun and Earth, blocking sunlight. Because the Moon's orbit is elliptical, its distance from Earth varies, changing the type of solar eclipse.",
    "개기 일식:": "Total Solar Eclipse:",
    "달이 지구에 가까울 때(근지점) 발생하며, 달의 겉보기 크기가 태양보다 커서 태양을 완전히 가립니다. 이때 태양의 코로나(대기)가 관측됩니다.": "Occurs when the Moon is closest to Earth (perigee). The Moon's apparent size is larger than the Sun, completely blocking it. The solar corona (atmosphere) can be observed.",
    "금환 일식:": "Annular Solar Eclipse:",
    "달이 지구에서 멀 때(원지점) 발생하며, 달의 겉보기 크기가 태양보다 작아 태양의 가장자리가 고리 모양으로 보입니다.": "Occurs when the Moon is farthest from Earth (apogee). The Moon's apparent size is smaller than the Sun, leaving a ring-like edge of the Sun visible.",
    "부분 일식:": "Partial Solar Eclipse:",
    "달이 태양의 일부만 가리는 현상으로, 관측자가 본그림자 밖 반그림자 영역에 있을 때 관측됩니다.": "Occurs when the Moon blocks only part of the Sun, visible when the observer is in the penumbra.",
    "2. 월식": "2. Lunar Eclipse",
    "월식은 지구가 태양과 달 사이에 위치하여 지구의 그림자가 달 표면에 드리워지는 현상입니다. 월식은 항상 보름달일 때 발생합니다.": "A lunar eclipse occurs when Earth is positioned between the Sun and Moon, casting Earth's shadow on the lunar surface. It always occurs during a full moon.",
    "개기 월식:": "Total Lunar Eclipse:",
    "달이 지구의 본그림자 안에 완전히 들어가는 현상입니다. 지구 대기가 붉은빛을 굴절시켜 달이 붉은색으로 보이며, 이를 '블러드 문'이라 부릅니다.": "Occurs when the Moon completely enters Earth's umbra. Earth's atmosphere refracts red light, making the Moon appear red, known as a 'Blood Moon'.",
    "부분 월식:": "Partial Lunar Eclipse:",
    "달의 일부만 본그림자에 걸치는 현상입니다.": "Occurs when only a part of the Moon enters the umbra.",
    "반영 월식:": "Penumbral Lunar Eclipse:",
    "달이 지구의 반그림자 영역만 통과하는 현상으로, 달의 밝기가 미세하게 어두워지며 육안으로 구분하기 어렵습니다.": "Occurs when the Moon passes only through Earth's penumbra. The Moon dims slightly, making it difficult to distinguish with the naked eye.",
    "3. 시뮬레이션 조작법": "3. Simulation Controls",
    "궤도 위치:": "Orbital Position:",
    "태양-지구-달의 상대적 각도를 조절합니다. 일식은 달이 태양 방향에 있을 때, 월식은 반대편에 있을 때 발생합니다.": "Adjusts the relative angles of the Sun, Earth, and Moon. Solar eclipses occur when the Moon is toward the Sun, and lunar eclipses when it's opposite.",
    "궤도 기울기:": "Orbital Inclination:",
    "달 궤도면과 지구 궤도면의 교차 각도를 조절합니다. 실제 달 궤도는 약 5° 기울어져 있어 매 보름달/초승달마다 식 현상이 일어나지 않습니다.": "Adjusts the intersection angle between the Moon's and Earth's orbital planes. The real lunar orbit is tilted by about 5°, so eclipses don't happen every full/new moon.",
    "달 거리 비율:": "Moon Distance Ratio:",
    "달의 근지점/원지점 거리를 조절하여 개기 일식과 금환 일식의 차이를 관찰할 수 있습니다.": "Adjusts the perigee/apogee distance to observe the difference between total and annular solar eclipses.",

    // Lens Simulation
    "볼록렌즈와 오목렌즈 시뮬레이션": "Convex & Concave Lens Simulation",
    "볼록렌즈 & 오목렌즈 시뮬레이션": "Convex & Concave Lens Simulation",
    "볼록렌즈": "Convex Lens",
    "오목렌즈": "Concave Lens",
    "광학 레일 실험": "Optical Rail Experiment",
    "광학 원리 설명": "Optical Principles",
    "화면의 물체(주황 화살표)나 초점(F)을 마우스로 직접 드래그하여 움직여보세요!": "Drag the object (orange arrow) or focus (F) directly on the screen to move them!",
    "렌즈를 통해 보이는 모습": "View through the Lens",
    "상태 설명 텍스트": "Status Description",
    "실험 문자 설정": "Letter Settings",
    "투영할 이미지 문자 선택:": "Select Letter for Projection:",
    "1번 렌즈 (볼록렌즈) 설정:": "Lens 1 (Convex) Settings:",
    "사용함": "Use",
    "사용 안 함": "Do Not Use",
    "2번 렌즈 (오목렌즈) 설정:": "Lens 2 (Concave) Settings:",
    "광학 벤치 제어": "Optical Bench Controls",
    "레일 시스템 제어": "Rail System Controls",
    "초점 거리 (f):": "Focal Length (f):",
    "물체 위치 (a / d₀):": "Object Position (a / d₀):",
    "물체 높이 (h₀):": "Object Height (h₀):",
    "1번 렌즈(볼록) 위치:": "Lens 1 (Convex) Position:",
    "2번 렌즈(오목) 위치:": "Lens 2 (Concave) Position:",
    "스크린 패널 위치:": "Screen Panel Position:",
    "광선 모드": "Ray Mode",
    "대표 광선 3개": "3 Principal Rays",
    "평행 레이저": "Parallel Lasers",
    "그리드 표시": "Show Grid",
    "보조선 및 치수 표시": "Show Guidelines",
    "실시간 측정 데이터": "Real-time Measurement Data",
    "렌즈 공식 계산식": "Lens Formula",
    "물체 거리 (a)": "Object Distance (a)",
    "상 거리 (b)": "Image Distance (b)",
    "배율 (m = -b/a)": "Magnification (m = -b/a)",
    "상태 판별": "Image Type",
    "1번 렌즈(볼록) 위치": "Lens 1 (Convex) Pos",
    "2번 렌즈(오목) 위치": "Lens 2 (Concave) Pos",
    "스크린 패널 위치": "Screen Panel Pos",
    "최종 초점 면 (Focal Plane)": "Final Focal Plane",
    "상의 배율 / 상태": "Image Magnification / State",
    "렌즈의 광학적 원리": "Optical Principles of Lenses",
    "1. 얇은 렌즈 공식 (Thin Lens Equation)": "1. Thin Lens Equation",
    "렌즈의 초점 거리를 $f$, 물체와 렌즈 중심 사이의 거리를 $a$, 상과 렌즈 중심 사이의 거리를 $b$라 할 때, 다음과 같은 공식이 성립합니다.": "When the focal length of the lens is $f$, the distance between the object and the lens center is $a$, and the distance between the image and the lens center is $b$, the following formula holds:",
    "부호 규약 (Sign Convention):": "Sign Convention:",
    "$a$ (물체 거리): 항상 양수($+$)": "$a$ (Object distance): Always positive ($+$)",
    "$f$ (초점 거리): 볼록렌즈는 양수($+$), 오목렌즈는 음수($-$)": "$f$ (Focal length): Positive ($+$) for convex, negative ($-$) for concave",
    "$b$ (상 거리): 실상은 양수($+$) (렌즈 통과 후 오른쪽에 형성), 허상은 음수($-$) (렌즈 앞쪽 왼쪽에 형성)": "$b$ (Image distance): Positive ($+$) for real image, negative ($-$) for virtual image",
    "2. 복합 렌즈 시스템 및 레일 실험 원리": "2. Compound Lens System & Rail Experiment Principles",
    "일반적인 광학 레일 시스템에서는 물체에서 나온 빛이 1번 렌즈(볼록렌즈)와 2번 렌즈(오목렌즈)를 순차적으로 통과하여 최종 스크린에 상을 맺습니다.": "In an optical rail system, light from the object sequentially passes through Lens 1 (convex) and Lens 2 (concave) to form an image on the screen.",
    "단계별 상 계산: 1번 렌즈에 의해 만들어진 상이 2번 렌즈의 새로운 물체 역할을 하게 됩니다.": "Step-by-step image calculation: The image formed by Lens 1 acts as a new object for Lens 2.",
    "초점 맞추기 (Focusing): 스크린의 위치가 2번 렌즈를 거친 최종 상의 거리와 정확히 일치할 때, 스크린에 가장 선명하고 뚜렷한 상(글자)이 맺히게 됩니다. 스크린이 초점 평면을 벗어나면 빛이 퍼지면서 글자가 흐릿해집니다(Blur).": "Focusing: When the screen is at the final image distance, the clearest image (letter) is formed. If not, the light spreads out and the image blurs.",
    "3. 렌즈 종류별 상의 특징": "3. Image Characteristics by Lens Type",
    "볼록렌즈 (수렴 렌즈):": "Convex Lens (Converging Lens):",
    "$a > 2f$ (초점 거리 2배 밖): <strong>축소된 도립 실상</strong> (카메라, 눈의 망막)": "$a > 2f$ (Beyond 2f): <strong>Reduced inverted real image</strong> (Camera, retina)",
    "$a = 2f$ (초점 거리 2배 지점): <strong>크기가 같은 도립 실상</strong>": "$a = 2f$ (At 2f): <strong>Same-size inverted real image</strong>",
    "$f < a < 2f$ (초점과 2배 초점 사이): <strong>확대된 도립 실상</strong> (영화 영사기)": "$f < a < 2f$ (Between f and 2f): <strong>Magnified inverted real image</strong> (Projector)",
    "$a < f$ (초점 안쪽): <strong>확대된 정립 허상</strong> (돋보기, 현미경 접안렌즈)": "$a < f$ (Inside f): <strong>Magnified upright virtual image</strong> (Magnifying glass, microscope)",
    "오목렌즈 (발산 렌즈):": "Concave Lens (Diverging Lens):",
    "물체의 위치에 관계없이 항상 렌즈 앞쪽에 <strong>축소된 정립 허상</strong>이 생깁니다. (근시 교정용 안경)": "Regardless of position, a <strong>reduced upright virtual image</strong> is formed in front of the lens (Myopia glasses).",

    // Specific text node breakdown for DOM tree structure in Lens Modal
    "단계별 상 계산:": "Step-by-step image calculation:",
    "1번 렌즈에 의해 만들어진 상이 2번 렌즈의 새로운 물체 역할을 하게 됩니다.": "The image formed by Lens 1 acts as a new object for Lens 2.",
    "초점 맞추기 (Focusing):": "Focusing:",
    "스크린의 위치가 2번 렌즈를 거친 최종 상의 거리와 정확히 일치할 때, 스크린에 가장 선명하고 뚜렷한 상(글자)이 맺히게 됩니다. 스크린이 초점 평면을 벗어나면 빛이 퍼지면서 글자가 흐릿해집니다(Blur).": "When the screen position exactly matches the distance of the final image after Lens 2, the clearest and sharpest image (letter) is formed on the screen. If the screen deviates from the focal plane, the light spreads out, causing the image to blur.",
    "$a > 2f$ (초점 거리 2배 밖):": "$a > 2f$ (Beyond twice the focal length):",
    "축소된 도립 실상": "Reduced inverted real image",
    "(카메라, 눈의 망막)": "(Camera, retina)",
    "$a = 2f$ (초점 거리 2배 지점):": "$a = 2f$ (At twice the focal length):",
    "크기가 같은 도립 실상": "Same-size inverted real image",
    "$f < a < 2f$ (초점과 2배 초점 사이):": "$f < a < 2f$ (Between focal length and twice the focal length):",
    "확대된 도립 실상": "Magnified inverted real image",
    "(영화 영사기)": "(Projector)",
    "$a < f$ (초점 안쪽):": "$a < f$ (Inside focal length):",
    "확대된 정립 허상": "Magnified upright virtual image",
    "(돋보기, 현미경 접안렌즈)": "(Magnifying glass, microscope eyepiece)",
    "물체의 위치에 관계없이 항상 렌즈 앞쪽에": "Regardless of the object's position, a",
    "축소된 정립 허상": "reduced upright virtual image",
    "이 생깁니다. (근시 교정용 안경)": "is always formed in front of the lens. (Myopia correction glasses)",
    
    // Lens Script Dynamic
    "물체": "Object",
    "도립 실상": "Inverted Real Image",
    "정립 허상": "Upright Virtual Image",
    "미사용": "Not Used",
    "평행 발산": "Parallel Divergence",
    "도립": "Inverted",
    "정립": "Upright",
    " 배": "x",
    "초점 위에 물체가 있어 상이 보이지 않음": "Object at focus: no image formed",
    "정립 허상 (돋보기: ": "Upright Virtual Image (Magnifier: ",
    "배 똑바로 확대)": "x, upright)",
    "도립 실상 (눈: ": "Inverted Real Image (Eye: ",
    "배 거꾸로 보임)": "x, inverted)",
    "정립 허상 (축소안경: ": "Upright Virtual Image (Diminishing Lens: ",
    "배 똑바로 축소)": "x, upright)",
    "렌즈 없음 (직사 광선 투영)": "No lens (Direct ray projection)",
    "✓ 초점이 정확히 맞았습니다!": "✓ Perfectly in focus!",
    "초점 오차: ": "Focal Error: ",
    "% (스크린을 움직여 맞추세요)": "% (Move screen to focus)",
    "스크린에 투영된 이미지 (패널 관측)": "Projected Screen Image (Panel View)",
    "광원 (물체)": "Light Source (Object)",
    "1번 볼록렌즈": "Lens 1 (Convex)",
    "2번 오목렌즈": "Lens 2 (Concave)",
    "스크린 패널": "Screen Panel",

    // Lenz's Law Simulation
    "렌츠의 법칙 시뮬레이션": "Lenz's Law Simulation",
    "자석과 코일": "Magnet & Coil",
    "금속 원판 낙하": "Metal Disk Drop",
    "LED 실험": "LED Experiment",
    "원리 설명": "Theory Guide",
    "자석 설정": "Magnet Settings",
    "자석 극성 방향:": "Magnet Polarity:",
    "N - S (좌N 우S)": "N - S (Left N, Right S)",
    "S - N (좌S 우N)": "S - N (Left S, Right N)",
    "자석 세기 (Magnetic Strength):": "Magnetic Strength:",
    "자동 운동 모드:": "Movement Mode:",
    "수동 (드래그)": "Manual (Drag)",
    "자동 왕복": "Auto-Oscillation",
    "코일 & 시각화 설정": "Coil & Visualization Settings",
    "코일 감은 수 (N):": "Coil Turns (N):",
    "자기장선 (Magnetic Field Lines) 표시": "Show Magnetic Field Lines",
    "유도 자기장 표시": "Show Induced Magnetic Field",
    "유도 전류 (전자 흐름) 표시": "Show Induced Current (Electron Flow)",
    "금속 원판 설정": "Metal Disk Settings",
    "금속 재질 선택:": "Select Metal Material:",
    "구리": "Copper",
    "알루미늄": "Aluminum",
    "황동": "Brass",
    "원판 형태:": "Disk Shape:",
    "꽉 찬 원판": "Solid Disk",
    "구멍 뚫린 원판": "Slotted Disk",
    "코일과 자석 설정": "Coil & Magnet Settings",
    "S극이 아래로": "S Pole Down",
    "N극이 아래로": "N Pole Down",
    "자기장선 표시": "Show Magnetic Field Lines",
    "유도 전류 방향(화살표) 표시": "Show Induced Current Direction",
    "N극 유도": "N-Pole Induced",
    "S극 유도": "S-Pole Induced",
    "유도 자기장 방향": "Induced Field Direction",
    "자기력(저항)": "Magnetic Force (Drag)",
    "렌츠의 법칙 및 전자기 유도 원리": "Lenz's Law & Electromagnetic Induction",
    "1. 패러데이의 전자기 유도 법칙 (Faraday's Law of Induction)": "1. Faraday's Law of Induction",
    "회로를 관통하는 자기선속(자속, Magnetic Flux $\\Phi$)이 시간적으로 변화할 때, 회로에 유도 기전력(유도 전압, $V$)이 발생하는 현상입니다.": "When the magnetic flux ($\\Phi$) passing through a circuit changes over time, an induced electromotive force (voltage, $V$) is generated in the circuit.",
    "코일의 감은 수 (감은 수가 많을수록 강한 유도 기전력 발생)": "Coil turns (higher turns produce stronger induced EMF)",
    "시간당 자속의 변화율 (자석이 빠르게 움직일수록 강한 유도 기전력 발생)": "Rate of change of magnetic flux (faster magnet motion produces stronger induced EMF)",
    "마이너스($-$) 부호:": "Minus sign ($$-$):",
    "렌츠의 법칙을 나타냅니다.": "represents Lenz's Law.",
    "2. 렌츠의 법칙 (Lenz's Law)": "2. Lenz's Law",
    "전자기 유도에 의해 발생하는 유도 전류의 방향은 **\"자속의 변화를 방해하려는 방향\"**으로 자기장을 만드는 방향으로 흐릅니다. 즉, 자연은 변화를 싫어하며 현재 상태를 유지하려고 저항하는 성질이 있습니다.": "The direction of the induced current is always such that it opposes the change in magnetic flux. In other words, nature resists change and attempts to maintain the status quo.",
    "자석이 코일에 다가올 때 (자속 증가)": "When magnet approaches coil (Flux increases)",
    "다가오는 자석을 밀어내기 위해 코일 앞부분에 <strong>자석의 극과 같은 극</strong>이 유도되어 척력이 발생합니다.": "To push away the approaching magnet, a **pole of the same type** is induced at the front of the coil, creating repulsive force.",
    "N극 접근 $\\rightarrow$ 코일 왼쪽에 N극 유도 (오른손 법칙으로 전류 방향 결정)": "N-pole approach $\\rightarrow$ N-pole induced on left of coil (current direction by right-hand rule)",
    "S극 접근 $\\rightarrow$ 코일 왼쪽에 S극 유도": "S-pole approach $\\rightarrow$ S-pole induced on left of coil",
    "자석이 코일에서 멀어질 때 (자속 감소)": "When magnet recedes from coil (Flux decreases)",
    "멀어지는 자석을 붙잡기 위해 코일 앞부분에 <strong>자석의 극과 반대 극</strong>이 유도되어 인력이 발생합니다.": "To attract the receding magnet, a **pole of the opposite type** is induced at the front of the coil, creating attractive force.",
    "N극 후퇴 $\\rightarrow$ 코일 왼쪽에 S극 유도": "N-pole recession $\\rightarrow$ S-pole induced on left of coil",
    "S극 후퇴 $\\rightarrow$ 코일 왼쪽에 N극 유도": "S-pole recession $\\rightarrow$ N-pole induced on left of coil",
    "3. 검류계(G)의 작동 원리": "3. Galvanometer (G) Principle",
    "검류계는 아주 미세한 전류의 크기와 방향을 측정하는 기기입니다. 전류가 시계 방향 혹은 반시계 방향으로 흐름에 따라 검류계의 바늘이 좌(+) 혹은 우(-)로 기울어져 유도 전류의 방향과 세기를 직관적으로 보여줍니다.": "A galvanometer measures the direction and magnitude of tiny currents. The needle tilts left or right depending on the current flow, showing the direction and strength intuitively.",

    // Periodic Table Simulation
    "인터랙티브 원소 주기율표 시뮬레이션": "Interactive Periodic Table Simulation",
    "원소 탐구 시뮬레이션": "Periodic Table & Element Simulator",
    "주기율표": "Periodic Table",
    "화합물 조합 실험실": "Compound Simulator Lab",
    "원소 이름, 번호 검색 (예: 수소, 1)...": "Search name, number (e.g. Hydrogen, 1)...",
    "모든 계열 전체": "All Categories",
    "알칼리 금속": "Alkali Metals",
    "알칼리 토금속": "Alkaline Earth Metals",
    "전이 금속": "Transition Metals",
    "전이후 금속": "Post-Transition Metals",
    "전이 후 금속": "Post-Transition Metals",
    "준금속": "Metalloids",
    "반응성 비금속": "Reactive Nonmetals",
    "비활성 기체": "Noble Gases",
    "란타넘족": "Lanthanides",
    "악티늄족": "Actinides",
    "미지 원소": "Unknown Category",
    "상온 상태 전체": "All States",
    "기체 (Gas)": "Gas",
    "액체 (Liquid)": "Liquid",
    "고체 (Solid)": "Solid",
    "기체": "Gas",
    "액체": "Liquid",
    "고체": "Solid",
    "인공 생성": "Synthetic",
    "히트맵 모드 꺼짐": "Heatmap Off",
    "원자량 스펙트럼": "Atomic Mass Spectrum",
    "원자량 (u)": "Atomic Mass (u)",
    "전기음성도": "Electronegativity",
    "전기음성도 (Pauling)": "Electronegativity (Pauling)",
    "녹는점 스펙트럼": "Melting Point Spectrum",
    "녹는점 (°C)": "Melting Point (°C)",
    "끓는점 스펙트럼": "Boiling Point Spectrum",
    "끓는점 (°C)": "Boiling Point (°C)",
    "이온화 에너지": "Ionization Energy",
    "이온화 에너지 (kJ/mol)": "Ionization Energy (kJ/mol)",
    "원자 반지름": "Atomic Radius",
    "원자 반지름 (pm)": "Atomic Radius (pm)",
    "밀도 스펙트럼": "Density Spectrum",
    "밀도 (g/cm³)": "Density (g/cm³)",
    "란타넘족 (57-70)": "Lanthanides (57-70)",
    "악티늄족 (89-102)": "Actinides (89-102)",
    "* 란타넘족 (57-70)": "* Lanthanides (57-70)",
    "** 악티늄족 (89-102)": "** Actinides (89-102)",
    "원자 구조 궤도 모형": "Atomic Structure Orbit Model",
    "원소 계열": "Category",
    "상온 상태": "State at Room Temp",
    "원자량": "Atomic Mass",
    "전자 배치": "Electron Config",
    "녹는점": "Melting Point",
    "끓는점": "Boiling Point",
    "밀도": "Density",
    "이전 원소": "Previous Element",
    "다음 원소": "Next Element",
    "원소 선택 팔레트": "Element Picker Palette",
    "반응 플라스크에 추가할 원소를 클릭하세요": "Click elements to add to the reaction flask",
    "반응 플라스크 & 화합물 검증": "Reaction Flask & Compound Validation",
    "왼쪽 팔레트에서 원소를 선택하여 플라스크에 채워보세요.": "Select elements from the left palette to fill the flask.",
    "화학 반응 실행!": "Run Chemical Reaction!",
    "대표 화합물 프리셋 가이드 (40종)": "Compound Preset Guide (40 Types)",
    "대표 화합물 프리셋 가이드": "Compound Preset Guide",
    "반응 성공": "Reaction Success",
    "결합 유형": "Bond Type",
    "반응 비율": "Reaction Ratio",
    "미확인 / 불안정 상태": "Unconfirmed / Unstable State",
    "시도된 화학 조합:": "Attempted Chemical Combination:",
    "현재 선택된 원소 비율로는 화학적으로 안정적인 대표 화합물을 형성하지 않습니다. 하단 프리셋 가이드를 참고하여 알맞은 비율을 맞춰보세요!": "The selected element ratio does not form a chemically stable compound. Refer to the preset guide below for correct ratios!",
    "공유결합": "Covalent Bond",
    "이온결합": "Ionic Bond",
    "극성 공유결합": "Polar Covalent Bond",
    "공유 결합": "Covalent Bond",
    "이온 결합": "Ionic Bond",
    "극성 공유 결합": "Polar Covalent Bond",

    // Common Compound Names
    "물": "Water",
    "이산화탄소": "Carbon Dioxide",
    "일산화탄소": "Carbon Monoxide",
    "염화나트륨 (소금)": "Sodium Chloride (Salt)",
    "메탄": "Methane",
    "암모니아": "Ammonia",
    "염산 / 염화수소": "Hydrochloric Acid / Hydrogen Chloride",
    "과산화수소": "Hydrogen Peroxide",
    "산화마그네슘": "Magnesium Oxide",
    "황산나트륨": "Sodium Sulfate",
    "포도당": "Glucose",
    "황산": "Sulfuric Acid",
    "질산": "Nitric Acid",
    "아세트산 (식초)": "Acetic Acid (Vinegar)",
    "탄산칼슘 (석회석)": "Calcium Carbonate (Limestone)",
    "에탄올 (알코올)": "Ethanol (Alcohol)",
    "수산화나트륨 (양잿물)": "Sodium Hydroxide (Lye)",
    "오존": "Ozone",
    "수소 기체": "Hydrogen Gas",
    "산소 기체": "Oxygen Gas",
    "질소 기체": "Nitrogen Gas",
    "염소 기체": "Chlorine Gas",
    "황화수소": "Hydrogen Sulfide",
    "이산화황": "Sulfur Dioxide",
    "산화철(III) (녹)": "Iron(III) Oxide (Rust)",
    "산화구리(II)": "Copper(II) Oxide",
    "황산구리": "Copper(II) Sulfate",
    "탄산수소나트륨 (베이킹소다)": "Sodium Bicarbonate (Baking Soda)",
    "플루오린화수소": "Hydrogen Fluoride",
    "염화칼륨": "Potassium Chloride",
    "수산화칼륨": "Potassium Hydroxide",
    "수산화칼슘 (소석회)": "Calcium Hydroxide (Slaked Lime)",
    "산화칼슘 (생석회)": "Calcium Oxide (Quicklime)",
    "에탄": "Ethane",
    "프로판": "Propane",
    "부탄": "Butane",
    "아세톤": "Acetone",
    "벤젠": "Benzene",
    "설탕 (자당)": "Sucrose (Sugar)",
    "폼알데하이드": "Formaldehyde",
    "원소를 선택하여 보어 원자 구조를 시뮬레이션하세요.": "Select an element to simulate Bohr atomic structure.",

    // H-R Diagram Simulation
    "별의 H-R도표 시뮬레이션": "H-R Diagram Simulation",
    "별의 H-R도표": "Hertzsprung-Russell (H-R) Diagram",
    "H-R도 탐구": "H-R Diagram Explorer",
    "별의 진화 실험실": "Stellar Evolution Lab",
    "항성 크기 비교실": "Star Scale Sandbox",
    "진화 진행:": "Evolution Progress:",
    "초기 질량:": "Initial Mass:",
    "속도:": "Speed:",
    "0.1x (슬로우)": "0.1x (Slow)",
    "모든 분류 전체": "All Categories",
    "없음 (항성 표시 숨김)": "None (Hide Stars)",
    "주계열성 (Main Sequence)": "Main Sequence",
    "적색거성 (Red Giant)": "Red Giant",
    "적색/청색 초거성 (Supergiant)": "Red/Blue Supergiant",
    "백색왜성 (White Dwarf)": "White Dwarf",
    "항성 이름": "Star Name",
    "진화 분류 / 분광형": "Spectral & Evolution Class",
    "표면 온도 (T)": "Surface Temp (T)",
    "광도 (L / L☉)": "Luminosity (L / L☉)",
    "반경 (R / R☉)": "Radius (R / R☉)",
    "중심부 핵 반응": "Core Fusion Reaction",
    "거리 / 예상 수명": "Distance / Est. Lifetime",
    "최종 진화 운명": "Final Evolution Fate",
    "H-R도 상의 별을 클릭하시면 세부 천문학 데이터와 진화 물리 설명이 표시됩니다.": "Click a star on the H-R diagram to view detailed astronomical data and evolutionary physics descriptions.",
    "유명 관측 별 선택 (클릭 시 상세 데이터 조회)": "Select Famous Stars (Click for details)",
    "진화 궤적 (Evolution Track) 시뮬레이터": "Evolution Track Simulator",
    "질량을 조절하면 별의 초기 원시성 단계부터 수소가 소진된 후 거성 팽창, 초신성 폭발, 왜성/블랙홀 이동 궤적이 그려집니다.": "Adjust mass to trace the evolution path from protostar, main sequence, giant expansion, supernova explosion, to dwarf/black hole.",
    "항성 실시간 3D/2D Visual": "Real-time Star Visual",
    "내부 핵융합 단면 보기": "View Core Cross-Section",
    "천체 상대적 반경 크기 비교 (Star Scale Sandbox)": "Star Scale Comparison Sandbox",
    "배율 Zoom:": "Zoom Scale:",
    "H-R도 및 항성 진화 천문학 가이드": "H-R Diagram & Stellar Evolution Guide",
    "1. H-R도 (Hertzsprung-Russell Diagram) 란?": "1. What is the H-R Diagram?",
    "2. 별의 분광형 (Spectral Types: O, B, A, F, G, K, M)": "2. Spectral Types (O, B, A, F, G, K, M)",
    "3. 슈테판-볼츠만 법칙과 등반경선 (Isoradius Lines)": "3. Stefan-Boltzmann Law & Isoradius Lines",
    "4. 질량에 따른 별의 최종 진화 운명": "4. Final Stellar Evolution Fates by Mass",

    // Canvas Labels & Text
    "적색 초거성 (Red Supergiants)": "Red Supergiants",
    "적색 거성 (Red Giants)": "Red Giants",
    "백색 왜성 (White Dwarfs)": "White Dwarfs",
    "주계열성 (Main Sequence)": "Main Sequence",
    "← 표면 온도 T (Kelvin, 대수 역축)": "← Surface Temperature T (Kelvin, log reversed)",
    "광도 L / L☉ (대수 축)": "Luminosity L / L☉ (log scale)",
    "절대 등급 (M_v)": "Absolute Magnitude (M_v)",
    "1 (태양)": "1 (Sun)",

    // Star Categories & Evolution Terms
    "주계열성": "Main Sequence",
    "적색거성": "Red Giant",
    "적색초거성": "Red Supergiant",
    "청색초거성": "Blue Supergiant",
    "청색거성": "Blue Giant",
    "백색왜성": "White Dwarf",
    "중성자별": "Neutron Star",
    "블랙홀": "Black Hole",
    "원시성": "Protostar",
    "준거성": "Subgiant",
    "수평가지": "Horizontal Branch",
    "점근거성가지": "Asymptotic Giant Branch (AGB)",
    "행성상 성운": "Planetary Nebula",
    "행성상 성운 분사": "Planetary Nebula Ejection",
    "행성상 성운 방출": "Planetary Nebula Ejection",
    "탄소-산소 백색왜성": "Carbon-Oxygen White Dwarf",
    "헬륨 백색왜성": "Helium White Dwarf",
    "O-Ne-Mg 백색왜성": "O-Ne-Mg White Dwarf",
    "II형 초신성 폭발 (Supernova)": "Type II Supernova Explosion",
    "중성자별 / 펄서 (Pulsar)": "Neutron Star / Pulsar",
    "볼프-레이에 성 (Wolf-Rayet)": "Wolf-Rayet Star",
    "적색 하이퍼거성": "Red Hypergiant",
    "극초신성 폭발 & 감마선 폭발": "Hypernova & Gamma-Ray Burst",
    "항성 질량 블랙홀 (Black Hole)": "Stellar Mass Black Hole",

    // Internal Shell Names
    "수소 (H) 외층": "Hydrogen (H) Envelope",
    "헬륨 (He) 껍질": "Helium (He) Shell",
    "탄소 (C) 껍질": "Carbon (C) Shell",
    "산소 (O) 껍질": "Oxygen (O) Shell",
    "네온/규소 (Ne/Si)": "Neon/Silicon (Ne/Si)",
    "철 (Fe) 코어 (붕괴 임계)": "Iron (Fe) Core (Collapse Critical)",
    "수소 (H) 대기": "Hydrogen (H) Atmosphere",
    "수소 껍질 융합층": "Hydrogen Shell Fusion Layer",
    "탄소-산소 (C-O) 코어": "Carbon-Oxygen (C-O) Core",
    "수소 (H) 전체 대류층": "Hydrogen (H) Convective Zone",
    "헬륨 (He) 중심부": "Helium (He) Core",

    // Star Names in Presets
    "태양 (Sun)": "Sun",
    "시리우스 A (Sirius A)": "Sirius A",
    "시리우스 B (Sirius B)": "Sirius B",
    "베텔게우스 (Betelgeuse)": "Betelgeuse",
    "리겔 (Rigel)": "Rigel",
    "알데바란 (Aldebaran)": "Aldebaran",
    "아크투루스 (Arcturus)": "Arcturus",
    "베가 (Vega)": "Vega",
    "북극성 (Polaris)": "Polaris",
    "프록시마 센타우리 (Proxima Centauri)": "Proxima Centauri",
    "안타레스 (Antares)": "Antares",
    "스피카 (Spica)": "Spica",
    "프로키온 A (Procyon A)": "Procyon A",
    "데네브 (Deneb)": "Deneb",
    "지구 (Earth)": "Earth",

    // Famous Star Descriptions
    "우리 태양계의 중심별로, 중심부에서 수소 핵융합(p-p chain)을 진행하고 있는 안정적인 G형 주계열성입니다.": "A stable G-type main-sequence star at the center of our solar system performing hydrogen fusion (p-p chain) in its core.",
    "밤하늘에서 가장 밝게 관측되는 대표적인 백색 주계열성입니다.": "The brightest star visible in the night sky, a prominent white main-sequence star.",
    "지구 크기 정도로 붕괴한 초고밀도 사체별로, 시리우스 A 주위를 궤도 운행하는 백색왜성입니다.": "An ultra-dense stellar remnant collapsed to Earth's size, orbiting Sirius A as a white dwarf.",
    "오리온자리의 어깨별로 궤도가 목성까지 미치는 거대한 적색초거성입니다. 머지않은 미래에 II형 초신성 폭발을 일으킵니다.": "A massive red supergiant at Orion's shoulder whose radius extends to Jupiter. It will undergo a Type II supernova explosion in the near future.",
    "오리온자리의 다리에 해당하는 웅장한 청색초거성으로, 엄청난 복사에너지를 발산합니다.": "A luminous blue supergiant at Orion's foot emitting immense radiative energy.",
    "황소자리의 붉은 눈에 해당하는 거성으로, 주계열 수소를 모두 태우고 적색거성으로 팽창하였습니다.": "The red eye of Taurus, a giant star that exhausted its main-sequence hydrogen and expanded into a red giant.",
    "목동자리의 주황색 주별로 중심부에서 헬륨 융합 반응이 활발히 일어나고 있는 거성입니다.": "The alpha star of Boötes, an orange giant star actively fusing helium in its core.",
    "거문고자리의 알파별이자 여름철 대삼각형을 형성하는 청백색 영천문학의 등급 기준별입니다.": "The alpha star of Lyra, forming the Summer Triangle, a blue-white standard reference star in astronomy.",
    "작은곰자리의 지축 방향 정렬별로, 주기적으로 반경이 맥동하는 세페이드 변광성 성격의 초거성입니다.": "The North Star in Ursa Minor, a Cepheid variable supergiant with periodically pulsating radius.",
    "태양계와 가장 가까운 이웃 항성으로 질량이 매우 작은 어두운 M형 적색왜성입니다.": "The closest neighboring star to the Solar System, a low-mass dim M-type red dwarf.",
    "전갈자리의 심장에 위치한 진붉은색 초대형 초거성입니다.": "A deep-red supergiant located at the heart of Scorpius.",
    "처녀자리의 가장 밝은 푸른색 거성입니다.": "The brightest blue giant star in Virgo.",
    "작은개자리의 주별로 수소 소진 단계에 진입한 준거성 특성의 황백색 별입니다.": "The main star of Canis Minor, a yellow-white subgiant entering hydrogen depletion.",
    "백조자리의 주별로, 수천 광년 거리에서도 눈부시게 빛나는 백색 초거성입니다.": "The primary star of Cygnus, a luminous white supergiant shining brightly even from thousands of light-years away.",

    // Star Distances & Lifetimes
    "0 광년 (1 AU)": "0 ly (1 AU)",
    "8.6 광년": "8.6 ly",
    "550 광년": "550 ly",
    "860 광년": "860 ly",
    "65.3 광년": "65.3 ly",
    "36.7 광년": "36.7 ly",
    "25.0 광년": "25.0 ly",
    "433 광년": "433 ly",
    "4.24 광년": "4.24 ly",
    "250 광년": "250 ly",
    "11.46 광년": "11.46 ly",
    "2600 광년": "2600 ly",
    "수천억 ~ 수조 년": "Hundreds of Billions to Trillions of Years",
    "수백만 년 이하": "Under a Few Million Years",
    "약 100억 년": "Approx. 10 Billion Years",
    "백만 년": "Million Years",
    "0억 년": "Billion Years",
    "광년": "ly",

    // Spectral Types & Colors
    "가장 뜨겁고 질량이 큰 항성 (스피카, O형 주계열)": "Hottest and most massive stars (Spica, O-type main sequence)",
    "표면온도가 매우 높은 별 (리겔)": "Stars with very high surface temperatures (Rigel)",
    "강한 수소 흡수선을 가지는 백색 항성 (시리우스A, 베가)": "White stars with strong hydrogen absorption lines (Sirius A, Vega)",
    "밝은 황백색 항성 (북극성, 프로키온A)": "Luminous yellow-white stars (Polaris, Procyon A)",
    "우리 태양과 같은 중간 질량 주계열성 (태양)": "Intermediate-mass main-sequence stars like our Sun (Sun)",
    "주황색 거성 및 왜성 (알데바란, 아크투루스)": "Orange giants and dwarfs (Aldebaran, Arcturus)",
    "가장 낮은 표면 온도를 지닌 적색 왜성 및 초거성 (베텔게우스, 프록시마)": "Red dwarfs and supergiants with lowest surface temperatures (Betelgeuse, Proxima)",
    "청백색": "Blue-White",
    "황백색": "Yellow-White",
    "황색": "Yellow",
    "주황색": "Orange",

    // Evolution Track Names & Outcomes
    "저질량 적색왜성": "Low-mass Red Dwarf",
    "태양형 별": "Sun-like Star",
    "중질량 별": "Intermediate-mass Star",
    "고질량 초거성": "High-mass Supergiant",
    "극대질량 하이퍼거성": "Hypergiant",
    "행성상 성운 + 탄소/산소 백색왜성": "Planetary Nebula + Carbon/Oxygen White Dwarf",
    "행성상 성운 + O-Ne-Mg 백색왜성": "Planetary Nebula + O-Ne-Mg White Dwarf",
    "II형 초신성 폭발 → 중성자별 (펄서)": "Type II Supernova → Neutron Star (Pulsar)",
    "극초신성 폭발 (Hypernova) → 블랙홀": "Hypernova Explosion → Black Hole",

    // Core Reactions
    "중력 수축": "Gravitational Contraction",
    "수소 핵융합": "Hydrogen Fusion",
    "전체 대류 수소 융합": "Convective Hydrogen Fusion",
    "헬륨 코어 축적": "Helium Core Accumulation",
    "전자 퇴적압 서서히 식음": "Electron Degeneracy Cooling",
    "수소 핵융합 (p-p chain)": "Hydrogen Fusion (p-p chain)",
    "수소 껍질 융합": "Hydrogen Shell Fusion",
    "헬륨 코어 중력 수축": "Helium Core Contraction",
    "헬륨 점화 (3-알파 반응)": "Helium Flash (Triple-Alpha Process)",
    "이중 껍질 융합 (H & He)": "Double Shell Fusion (H & He)",
    "외층 방출": "Envelope Ejection",
    "전자 퇴적압 식음": "Electron Degeneracy Cooling",
    "CNO 수소 융합": "CNO Hydrogen Fusion",
    "헬륨 및 탄소 융합": "Helium & Carbon Fusion",
    "중심부 헬륨 융합": "Core Helium Fusion",
    "외층 가스 방출": "Envelope Gas Ejection",
    "전자 퇴적압": "Electron Degeneracy Pressure",
    "CNO 고속 융합": "Rapid CNO Fusion",
    "철(Fe) 코어 반응까지 연속 융합": "Sequential Fusion up to Iron (Fe) Core",
    "철 코어 중력 붕괴": "Iron Core Gravitational Collapse",
    "중성자 퇴적압": "Neutron Degeneracy Pressure",
    "초고속 중력 붕괴": "Ultra-fast Gravitational Collapse",
    "극초고속 CNO 융합": "Extreme CNO Fusion",
    "강력 항성풍 물질 방출": "Strong Stellar Wind Ejection",
    "철 코어 형성": "Iron Core Formation",
    "직접 블랙홀 중력 붕괴": "Direct Black Hole Collapse",
    "특이점 붕괴": "Singularity Collapse",
    "핵 반응:": "Core Fusion:",

    // Evolution Stage Descriptions
    "거대한 가스 구름이 중력 수축하며 원시 항성으로 형성됩니다.": "Formed as a massive gas cloud collapses under gravity into a protostar.",
    "중심 온도가 약 1,000만 K에 달하여 안정적 수소 핵융합이 진행됩니다.": "Core temperature reaches ~10 million K, initiating stable hydrogen fusion.",
    "별 전체 대류로 내부 수소를 남김없이 소비하므로 우주 나이보다 더 오래 생존합니다.": "Fully convective, consuming hydrogen completely and outliving the age of the universe.",
    "수소가 모두 헬륨으로 변환되며 표면온도가 상승합니다.": "Hydrogen is fully converted to helium, causing surface temperature to rise.",
    "거성 팽창 단계를 거치지 않고 식어가는 헬륨 백색왜성이 됩니다.": "Cools into a helium white dwarf without undergoing giant expansion.",
    "성간 물질 붕괴로 형성된 원시별 단계입니다.": "Protostar phase formed by the collapse of interstellar matter.",
    "수소를 헬륨으로 융합하며 정역학적 평형을 유지합니다.": "Fuses hydrogen into helium, maintaining hydrostatic equilibrium.",
    "중심 수소가 소진되어 껍질 융합으로 외층이 팽창하기 시작합니다.": "Core hydrogen is depleted; shell fusion begins and the envelope expands.",
    "외층이 거대하게 팽창하여 적색거성이 됩니다.": "The outer layers expand enormously into a red giant.",
    "중심부 헬륨이 폭발적으로 점화하여 탄소와 산소를 생성합니다.": "Core helium ignites explosively, producing carbon and oxygen.",
    "중심 탄소 코어 주위에서 이중 껍질 융합 반응이 일어납니다.": "Double-shell fusion occurs around the central carbon core.",
    "불안정한 열 맥동으로 외층 가스를 우주 공간으로 방출합니다.": "Thermal pulsations expel the outer gas envelope into space.",
    "초고밀도 중심 코어가 남아 백색왜성으로 천천히 식어갑니다.": "An ultra-dense central core remains, slowly cooling into a white dwarf.",
    "빠른 중력 수축 단계입니다.": "Rapid gravitational contraction phase.",
    "CNO 순환 반응으로 수소를 빠르게 소비합니다.": "Rapidly consumes hydrogen via the CNO cycle.",
    "광도가 매우 높아진 팽창 단계입니다.": "Expanded phase with significantly increased luminosity.",
    "H-R도 상에서 고온 청색 구역으로 이동하는 주기입니다.": "Loop moving toward high-temperature blue region on the H-R diagram.",
    "강력한 성운 방출을 일으킵니다.": "Causes powerful planetary nebula ejection.",
    "대질량 백색왜성이 됩니다.": "Becomes a massive white dwarf.",
    "격렬한 아웃보스트와 함께 탄생합니다.": "Born with violent outbursts.",
    "강력한 자외선을 뿜어내는 청색 거대 주계열성입니다.": "Massive blue main-sequence star emitting intense ultraviolet radiation.",
    "높은 광도를 자랑합니다.": "Boasts exceptionally high luminosity.",
    "H->He->C->O->Ne->Si->Fe 양파 껍질 핵융합 구조가 완성됩니다.": "Completed H->He->C->O->Ne->Si->Fe onion-shell nuclear fusion structure.",
    "철 코어 중력 붕괴로 은하 전체보다 밝은 무서운 폭발이 일어납니다!": "Iron core collapses, triggering a colossal explosion brighter than an entire galaxy!",
    "반경 10km의 초고밀도 중성자별이 탄생하여 고속 자전 자기장 빔을 사출합니다.": "An ultra-dense 10km neutron star forms, emitting rapid-rotating magnetic beams.",
    "엄청난 가스 물질 붕괴로 형성됩니다.": "Formed by catastrophic collapse of massive gas clouds.",
    "복사압이 항성을 찢을 만큼 강력한 최상위 주계열성입니다.": "Extreme top-tier main-sequence star with radiation pressure strong enough to tear itself apart.",
    "자신의 외각층을 폭풍처럼 분사합니다.": "Ejects its outer layers in tempestuous stellar winds.",
    "우주에서 가장 거대한 반경의 항성이 됩니다.": "Expands into one of the largest radius stars in the universe.",
    "강력한 감마선 버스트와 함께 폭발합니다!": "Explodes violently with intense gamma-ray bursts!",
    "빛조차 탈출할 수 없는 시공간 굴절 블랙홀이 탄생합니다.": "A spacetime-warping black hole is born from which even light cannot escape.",

    // Modal Section 4 & Compound Terms
    "저질량 별 ($< 0.5 M_\\odot$)": "Low-mass Star ($< 0.5 M_\\odot$)",
    ": 거성 팽창 없이 직접 헬륨 백색왜성으로 서서히 식어감.": ": Slowly cools directly into a helium white dwarf without giant expansion.",
    "거성 팽창 없이 직접 헬륨 백색왜성으로 서서히 식어감.": "Slowly cools directly into a helium white dwarf without giant expansion.",
    "태양형 별 ($0.8 \\sim 8 M_\\odot$)": "Sun-like Star ($0.8 \\sim 8 M_\\odot$)",
    ": 주계열성 $\\rightarrow$ 적색거성 $\\rightarrow$ 행성상 성운 분사 $\\rightarrow$ 탄소-산소 백색왜성.": ": Main Sequence $\\rightarrow$ Red Giant $\\rightarrow$ Planetary Nebula Ejection $\\rightarrow$ Carbon-Oxygen White Dwarf.",
    "주계열성 $\\rightarrow$ 적색거성 $\\rightarrow$ 행성상 성운 분사 $\\rightarrow$ 탄소-산소 백색왜성.": "Main Sequence $\\rightarrow$ Red Giant $\\rightarrow$ Planetary Nebula Ejection $\\rightarrow$ Carbon-Oxygen White Dwarf.",
    "고질량 별 ($> 8 M_\\odot$)": "High-mass Star ($> 8 M_\\odot$)",
    ": 청색주계열성 $\\rightarrow$ 적색초거성(철 코어 산출) $\\rightarrow$ II형 초신성 폭발 $\\rightarrow$ 중성자별(펄서) 또는 블랙홀.": ": Blue Main Sequence $\\rightarrow$ Red Supergiant (Iron Core) $\\rightarrow$ Type II Supernova $\rightarrow$ Neutron Star (Pulsar) or Black Hole.",
    "청색주계열성 $\\rightarrow$ 적색초거성(철 코어 산출) $\\rightarrow$ II형 초신성 폭발 $\\rightarrow$ 중성자별(펄서) 또는 블랙홀.": "Blue Main Sequence $\\rightarrow$ Red Supergiant (Iron Core) $\\rightarrow$ Type II Supernova $\rightarrow$ Neutron Star (Pulsar) or Black Hole.",
    "청색주계열성": "Blue Main Sequence",
    "철 코어 산출": "Iron Core",
    "(철 코어 산출)": "(Iron Core)",
    "II형 초신성 폭발": "Type II Supernova",
    "(펄서) 또는": "(Pulsar) or",
    "탄소-산소 백색왜성": "Carbon-Oxygen White Dwarf",
    "탄소-산소": "Carbon-Oxygen",
    "탄소-": "Carbon-",

    // Single Star Names for Preset Chips
    "태양": "Sun",
    "시리우스": "Sirius",
    "베텔게우스": "Betelgeuse",
    "리겔": "Rigel",
    "알데바란": "Aldebaran",
    "아크투루스": "Arcturus",
    "베가": "Vega",
    "북극성": "Polaris",
    "프록시마": "Proxima",
    "안타레스": "Antares",
    "스피카": "Spica",
    "프로키온": "Procyon",
    "데네브": "Deneb",

    // Blackbody Radiation Simulation (흑체복사시뮬레이션)
    "별과 흑체 복사 시뮬레이션": "Star & Blackbody Radiation Simulation",
    "1. 플랑크 곡선 & 색상": "1. Planck Curve & Color",
    "2. 광도 & 법칙": "2. Luminosity & Laws",
    "3. 항성 비교": "3. Star Comparison",
    "별의 복사 에너지 분포": "Stellar Radiative Energy Distribution",
    "표면 온도 (T):": "Surface Temp (T):",
    "대표 온도의 별:": "Representative Temp Stars:",
    "3,000 K (붉은색 별)": "3,000 K (Red Star)",
    "4,000 K (주황색 별)": "4,000 K (Orange Star)",
    "5,778 K (태양)": "5,778 K (Sun)",
    "13,000 K (청백색 별)": "13,000 K (Blue-White Star)",
    "자외선 (< 400 nm)": "Ultraviolet (< 400 nm)",
    "가시광선 (400 ~ 700 nm)": "Visible Light (400 ~ 700 nm)",
    "적외선 (> 700 nm)": "Infrared (> 700 nm)",
    "핵심 관측 데이터": "Key Observational Data",
    "최대 방출 파장 (λmax)": "Peak Emission Wavelength (λmax)",
    "단위 면적당 방출 에너지 (E)": "Energy Emitted per Unit Area (E)",
    "태양 단위 면적당 에너지를 1로 볼 때의 상대 비": "Relative ratio with Sun's unit area energy as 1",
    "온도가 높을수록 모든 파장 영역에서 더 많은 에너지를 방출하며, 복사 에너지를 최대 세기로 방출하는 파장(λmax)은 짧아져 청색으로 보입니다.": "Higher temperatures emit more energy across all wavelengths, and the peak emission wavelength (λmax) becomes shorter, shifting to blue.",
    "별의 실제 크기 & 에너지 방출 시각화": "Star Physical Size & Energy Emission Visual",
    "별 반지름 (R / R☉):": "Star Radius (R / R☉):",
    "광도(L) 핵심 관측 수치": "Luminosity (L) Key Observational Metrics",
    "별의 총 광도 (L)": "Total Luminosity of Star (L)",
    "태양 총 밝기(광도) 대비 배율": "Ratio relative to total Sun brightness",
    "온도가 올라갈수록 T4배로 급증": "Increases drastically by factor of T⁴ as temp rises",
    "별의 표면적 (4π R2)": "Surface Area of Star (4π R²)",
    "반지름이 2배가 되면 표면적은 4배가 됨": "Doubling radius quadruples surface area",
    "별의 총 광도(L)는 표면적(R2)과 단위 면적당 방출 에너지(T4)의 곱에 의해 결정됩니다.": "Total luminosity (L) is determined by the product of surface area (R²) and energy per unit area (T⁴).",
    "항성 A 선택": "Select Star A",
    "항성 B 선택": "Select Star B",
    "두 별의 복사 스펙트럼 및 물성 비교": "Compare Radiation Spectrum & Properties of Two Stars",
    "온도 비 (TB / TA)": "Temp Ratio (T_B / T_A)",
    "반지름 비 (RB / RA)": "Radius Ratio (R_B / R_A)",
    "단위면적 에너지 비 (EB / EA)": "Unit Energy Ratio (E_B / E_A)",
    "총 광도 비 (LB / LA)": "Total Luminosity Ratio (L_B / L_A)",
    "별과 흑체 복사 설명": "Stars & Blackbody Radiation Guide",
    "1. 흑체(Blackbody)와 별의 복사": "1. Blackbody & Stellar Radiation",
    "흑체란 자신에게 입사되는 모든 전자기파 에너지를 100% 흡수하고, 흡수한 에너지를 복사의 형태로 모두 방출하는 이상적인 물체입니다. 별은 흑체에 가까운 성질을 지니고 있어, 표면 온도에 따라 각 파장에서 방출하는 복사 에너지의 양과 색깔이 결정됩니다.": "A blackbody is an ideal object that absorbs 100% of incident electromagnetic radiation and re-emits all absorbed energy as radiation. Stars behave closely like blackbodies, where surface temperature determines the color and amount of energy emitted across all wavelengths.",
    "2. 플랑크 곡선과 별의 색상": "2. Planck Curve & Stellar Color",
    "흑체의 표면 온도(T)가 높아질수록 모든 파장 영역에서 더 많은 복사 에너지를 방출합니다. 또한 에너지를 가장 강하게 방출하는 파장(λmax)은 온도가 높을수록 짧아져 파란색 방향으로 이동합니다.": "As blackbody surface temperature (T) rises, more radiation energy is emitted across all wavelengths. Additionally, the peak emission wavelength (λmax) becomes shorter, shifting toward blue.",
    "고온의 별 (예: 리겔 ~12,100 K)": "Hot star (e.g. Rigel ~12,100 K)",
    ": 최대 방출 파장이 짧아 청백색으로 보입니다.": ": Peak wavelength is short, appearing blue-white.",
    "저온의 별 (예: 베텔게우스 ~3,500 K)": "Cool star (e.g. Betelgeuse ~3,500 K)",
    ": 최대 방출 파장이 길어 붉은색으로 보입니다.": ": Peak wavelength is long, appearing red.",
    "3. 슈테판 · 볼츠만 법칙": "3. Stefan-Boltzmann Law",
    "흑체가 단위 시간 동안 단위 면적에서 방출하는 복사 에너지 양(E)은 표면 온도(T)의 4제곱에 비례합니다. 표면 온도가 2배가 되면 단위 면적당 방출 에너지는 24 = 16배가 됩니다.": "The energy emitted per unit area per unit time (E) by a blackbody is proportional to the 4th power of surface temperature (T). Doubling the surface temperature increases unit area energy by 2⁴ = 16 times.",
    "4. 별의 광도(L)와 반지름(R)의 관계": "4. Relationship Between Luminosity (L) & Radius (R)",
    "전체 표면에서 방출하는 에너지를 뜻하므로, 반지름의 제곱(R2)과 표면 온도의 4제곱(T4)의 곱에 비례합니다.": "Since it represents energy emitted across the entire surface, it is proportional to the product of radius squared (R²) and temperature to the 4th power (T⁴).",
    "확인 및 탐구 계속하기": "Confirm & Continue Exploring",
    "1.0 R☉ (태양 기준 크기)": "1.0 R☉ (Sun Reference Scale)",

    // Exact Split Text Node Fragments for Blackbody Simulation
    "표면 온도 (": "Surface Temp (",
    "별 반지름 (": "Star Radius (",
    "광도(": "Luminosity(",
    ") 핵심 관측 수치": ") Key Metrics",
    "최대 방출 파장 (λ": "Peak Wavelength (λ",
    "단위 면적당 방출 에너지 (": "Energy Emitted per Unit Area (",
    "단위 면적당 에너지 (": "Unit Area Energy (",
    "별의 총 광도 (": "Total Luminosity of Star (",
    "온도가 올라갈수록 ": "Increases drastically by factor of ",
    "배로 급증": " as temp rises",
    "별의 표면적 (4π ": "Surface Area of Star (4π ",
    " 핵심 포인트": " Key Point",
    "반지름 (": "Radius (",
    "최대 방출 파장 (": "Peak Wavelength (",
    "총 광도 (": "Total Luminosity (",
    "온도 비 (": "Temp Ratio (",
    "반지름 비 (": "Radius Ratio (",
    "단위면적 에너지 비 (": "Unit Energy Ratio (",
    "총 광도 비 (": "Total Luminosity Ratio (",
    "설명": "Guide",

    // Modal Text Nodes
    " 별과 흑체 복사 설명": " Stars & Blackbody Radiation Guide",
    "1. 흑체(Blackbody)와 별의 복사": "1. Blackbody & Stellar Radiation",
    "흑체": "A blackbody",
    "란 자신에게 입사되는 모든 전자기파 에너지를 100% 흡수하고, 흡수한 에너지를 복사의 형태로 모두 방출하는 이상적인 물체입니다. 별은 흑체에 가까운 성질을 지니고 있어, 표면 온도에 따라 각 파장에서 방출하는 복사 에너지의 양과 색깔이 결정됩니다.": " is an ideal object that absorbs 100% of incident electromagnetic radiation and re-emits all absorbed energy as radiation. Stars behave closely like blackbodies, where surface temperature determines the color and amount of energy emitted across all wavelengths.",
    "흑체의 표면 온도(": "As blackbody surface temperature (",
    ")가 높아질수록 ": ") rises, ",
    "모든 파장 영역에서 더 많은 복사 에너지": "more radiation energy across all wavelengths",
    "를 방출합니다. 또한 에너지를 가장 강하게 방출하는 파장(λ": " is emitted. Additionally, peak emission wavelength (λ",
    ")은 온도가 높을수록 ": ") becomes ",
    "짧아져 파란색 방향": "shorter, shifting toward blue",
    "으로 이동합니다.": ".",
    "3. 슈테판 · 볼츠만 법칙": "3. Stefan-Boltzmann Law",
    "흑체가 단위 시간 동안 ": "Energy emitted per unit area (",
    "단위 면적에서 방출하는 복사 에너지 양(": "",
    "은 표면 온도(": " by a blackbody is proportional to ",
    ")의 ": "'s ",
    "4제곱에 비례": "4th power",
    "4제곱에 비례합니다.": "4th power.",
    " 표면 온도가 2배가 되면 단위 면적당 방출 에너지는 2": ". Doubling the surface temperature increases energy by 2",
    "표면 온도가 2배가 되면 단위 면적당 방출 에너지는 2": "Doubling the surface temperature increases energy by 2",
    " = 16배가 됩니다.": " = 16 times.",
    " = 16배.": " = 16 times.",
    "4. 별의 광도(": "4. Relationship Between Luminosity (",
    ")와 반지름(": ") & Radius (",
    ")의 관계": ")",
    " = (별의 표면적 4π ": " = (Star Surface Area 4π ",
    ") × (단위 면적당 에너지 σ ": ") × (Unit Area Energy σ ",
    "전체 표면에서 방출하는 에너지를 뜻하므로, ": "Since it represents energy emitted across the entire surface, it is ",
    "반지름의 제곱(": "proportional to the product of radius squared (",
    ")과 표면 온도의 4제곱(": ") and temperature to the 4th power (",
    ")의 곱에 비례": ")",
    ")의 곱에 비례합니다.": ").",
    "4제곱에 비례합니다.": "4th power.",
    "짧아져 파란색 방향으로 이동합니다.": "shorter, shifting toward blue.",
    "짧아져 청색으로 보입니다.": "shorter, shifting to blue.",
    ")의 곱에 의해 결정됩니다.": ").",
    "모든 파장 영역에서 더 많은 에너지": "more energy across all wavelengths",
    "별의 총 광도(": "Total luminosity (",
    ")는 ": " is determined by the ",
    "표면적(": "product of surface area (",
    ")과 단위 면적당 방출 에너지(": ") and unit area energy (",
    "프록시마 센타우리 (Proxima Centauri)": "Proxima Centauri",
    "프록시마 센타우리": "Proxima Centauri",
    "온도가 높을수록 ": "Higher temperatures emit ",
    "를 방출하며, 복사 에너지를 최대 세기로 방출하는 파장(λ": ", and the peak emission wavelength (λ",
    ")은 ": ") becomes ",
    "짧아져 청색": "shorter, shifting to blue",
    "으로 보입니다.": ".",

    // ==================== 부력과 아르키메데스 원리 시뮬레이션 ====================
    "부력과 아르키메데스 원리": "Buoyancy & Archimedes' Principle",
    "부력과 아르키메데스 원리 시뮬레이션": "Buoyancy & Archimedes' Principle Simulation",
    "1. 아르키메데스 원리 & 힘 분석": "1. Archimedes' Principle & Force Analysis",
    "2. 배 & 잠수함 원리": "2. Ship & Submarine Principle",
    "3. 열기구 (기체 부력)": "3. Hot Air Balloon (Gas Buoyancy)",
    "원리 설명": "Theory & Concepts",
    "원리 설명 보기": "View Theory & Concepts",
    "물체 상태: 떠오름": "Object Status: Floating",
    "물체 상태: 중성 부력": "Object Status: Neutral Buoyancy",
    "물체 상태: 가라앉음": "Object Status: Sinking",
    "잠긴 부피: 0%": "Submerged Volume: 0%",
    "힘 화살표": "Force Arrows",
    "힘 화살표 토글": "Toggle Force Arrows",
    "중력 Fg = ": "Gravity Fg = ",
    "부력 Fb = ": "Buoyancy Fb = ",
    "대기 부력 Fb = ": "Atmospheric Buoyancy Fb = ",
    "총 중력 Fg = ": "Total Gravity Fg = ",
    "물체를 마우스로 드래그하여 유체 속 깊이를 조절해보세요! 손을 놓으면 물리 법칙에 따라 움직입니다.": "Drag the object with your mouse to adjust fluid depth! Release to watch physical motion.",
    "물체 설정": "Object Settings",
    "재질 프리셋": "Material Presets",
    "목재 (0.6g/cm³)": "Wood (0.6g/cm³)",
    "얼음 (0.92g/cm³)": "Ice (0.92g/cm³)",
    "플라스틱 (0.95g/cm³)": "Plastic (0.95g/cm³)",
    "알루미늄 (2.7g/cm³)": "Aluminum (2.7g/cm³)",
    "철 (7.87g/cm³)": "Iron (7.87g/cm³)",
    "금 (19.3g/cm³)": "Gold (19.3g/cm³)",
    "물체 밀도 (ρ물체)": "Object Density (ρ_obj)",
    "물체 부피 (V)": "Object Volume (V)",
    "유체 & 환경 설정": "Fluid & Environment Settings",
    "유체 프리셋": "Fluid Presets",
    "물 (1.00g/cm³)": "Water (1.00g/cm³)",
    "순수한 물": "Pure Water",
    "바닷물 (1.03g/cm³)": "Seawater (1.03g/cm³)",
    "식용유 (0.92g/cm³)": "Cooking Oil (0.92g/cm³)",
    "에탄올 (0.79g/cm³)": "Ethanol (0.79g/cm³)",
    "사해 (1.24g/cm³)": "Dead Sea (1.24g/cm³)",
    "사해(소금물)": "Dead Sea (Saltwater)",
    "수은 (13.6g/cm³)": "Mercury (13.6g/cm³)",
    "유체 밀도 (ρ유체)": "Fluid Density (ρ_fluid)",
    "중력 가속도 (g)": "Gravitational Accel (g)",
    "모드: 철강 선박 (부력 형성)": "Mode: Steel Ship (Buoyancy)",
    "흘수선 높이: 45%": "Draft Line Height: 45%",
    "수상 선박 모드": "Surface Ship Mode",
    "잠수함 모드": "Submarine Mode",
    "화물 무게를 추가하거나 잠수함 바수조(Ballast Tank)의 물/공기 비율을 조절해보세요!": "Add cargo weight or adjust the water/air ratio in the submarine ballast tank!",
    "화물 적재 (선박 모드)": "Cargo Loading (Ship Mode)",
    "선체 배치 화물 개수": "Cargo Count on Deck",
    "선체 내부 중공(공기층) 부피": "Hollow Hull (Air Space) Volume",
    "💡 선박 부력 핵심": "💡 Ship Buoyancy Core Principle",
    "철(7.87 g/cm³)도 속을 비워 내부 부피를 크게 만들어 배의 평소 밀도를 물(1.0 g/cm³)보다 낮추면 크게 떠오릅니다!": "Even iron (7.87 g/cm³) floats high if made hollow to increase internal volume, lowering average density below water (1.0 g/cm³)!",
    "벨러스트 탱크 (잠수함 모드)": "Ballast Tank (Submarine Mode)",
    "탱크 내부 주입 물 비율 (%)": "Water Filling Ratio in Tank (%)",
    "부상 (공기 주입)": "Surface (Inject Air)",
    "정지 (중성 부력)": "Hover (Neutral Buoyancy)",
    "잠수 (물 주입)": "Dive (Inject Water)",
    "💡 잠수함의 침강/부상 원리": "💡 Submarine Surfacing & Diving Principle",
    "밸러스트 탱크에 물을 채우면 무게가 늘어나 평균 밀도가 물보다 커져 잠수하고, 압축 공기로 물을 밀어내면 평균 밀도가 낮아져 부상합니다.": "Filling ballast tanks with water increases weight so average density exceeds water to dive; expelling water with compressed air lowers average density to surface.",
    "상태: 고도 유지 중": "Status: Maintaining Altitude",
    "현재 고도: 120 m": "Current Altitude: 120 m",
    "버너 화력을 조절하여 공기를 가열하세요! 가열된 공기는 밀도가 낮아져 대기 부력을 받습니다.": "Adjust burner power to heat the air! Heated air lowers density and gains atmospheric buoyancy.",
    "열기구 가열 제어": "Hot Air Balloon Heating Control",
    "버너 가열 화력": "Burner Heating Power",
    "열기구 내 공기 온도": "Air Temp inside Balloon",
    "탑승 화물/승객 무게": "Cargo & Passenger Weight",
    "🎈 기체 부력 공식": "🎈 Gas Buoyancy Formula",
    "공기는 가열할수록 기체 분자 운동이 활발해져 밀도(ρ)가 작아집니다.": "As air is heated, gas molecular motion increases, reducing air density (ρ).",
    "부력과 아르키메데스의 원리 개념 정리": "Buoyancy & Archimedes' Principle Concepts",
    "1. 부력이란?": "1. What is Buoyancy?",
    "유체(액체나 기체) 속에 놓인 물체가 유체로부터 위쪽 방향으로 받는 힘을 ": "The upward force exerted by a fluid (liquid or gas) on an object placed inside it is called ",
    "부력": "buoyancy",
    "이라고 합니다.": ".",
    "액체 속 깊이가 깊어질수록 수압이 증가하기 때문에 물체의 아래쪽 면에 작용하는 위쪽 수압이 상단 면에 작용하는 아래쪽 수압보다 커서 알짜 힘이 위쪽으로 발생합니다.": "Because water pressure increases with depth, upward pressure on the bottom face exceeds downward pressure on the top face, generating a net upward force.",
    "2. 아르키메데스의 원리": "2. Archimedes' Principle",
    "유체 속에 잠긴 물체가 받는 부력의 크기는 물체가 밀어낸 유체의 무게와 정확히 같다!": "The magnitude of buoyant force on a submerged object equals the weight of the fluid displaced by the object!",
    "유체의 밀도 (kg/m³ 또는 g/cm³)": "Fluid density (kg/m³ or g/cm³)",
    "물체가 유체 속에 잠긴 부피 (m³ 또는 cm³)": "Submerged volume of object (m³ or cm³)",
    "중력 가속도 (m/s²)": "Gravitational acceleration (m/s²)",
    "3. 물체의 떠오름, 가라앉음, 정지 조건": "3. Floating, Sinking & Equilibrium Conditions",
    "떠오름": "Floating",
    "중력보다 부력이 커서 위로 부유하며, 잠긴 부피의 비율만큼만 물에 잠겨 평형(Fg = Fb)을 이룹니다.": "Buoyancy exceeds gravity so it floats upward, reaching equilibrium (Fg = Fb) when the submerged volume fraction balances weight.",
    "중성 부력": "Neutral Buoyancy",
    "유체 속 임의의 깊이에 가만히 정지해 있습니다 (예: 잠수함 호버링).": "Stays motionless at any depth within the fluid (e.g. submarine hovering).",
    "가라앉음": "Sinking",
    "중력이 최대 부력보다 커서 바닥까지 가라앉습니다. (물속 겉보기 무게 = 중력 - 부력)": "Gravity exceeds maximum buoyancy so it sinks to the bottom. (Apparent weight underwater = Gravity - Buoyancy)",
    
    // Node splitting exact matches for Buoyancy Simulation
    "중력 F": "Gravity F",
    "부력 F": "Buoyancy F",
    "대기 부력 F": "Atmospheric Buoyancy F",
    "총 중력 F": "Total Gravity F",
    "9.80 m/s² (지구)": "9.80 m/s² (Earth)",
    "(지구)": "(Earth)",
    "2 개 (총 200kg)": "2 pcs (Total 200kg)",
    " 개 (총 ": " pcs (Total ",
    "철(7.87 g/cm³)도 속을 비워 내부 부피를 크게 만들어 배의 평균 밀도를 물(1.0 g/cm³)보다 낮추면 크게 떠오릅니다!": "Even iron (7.87 g/cm³) floats high if made hollow to increase internal volume, lowering average density below water (1.0 g/cm³)!",
    "외부공기": "outside_air",
    "내부공기": "inside_air",
    "열기구": "balloon",
    "유체": "fluid",
    "잠김": "submerged",
    "물체": "object",
    ": 유체의 밀도 (kg/m³ 또는 g/cm³)": ": Fluid density (kg/m³ or g/cm³)",
    ": 물체가 유체 속에 잠긴 부피 (m³ 또는 cm³)": ": Submerged volume of object (m³ or cm³)",
    "중력보다 부력이 커서 위로 부유하며, 잠긴 부피의 비율만큼만 물에 잠겨 평형(F": "Buoyancy exceeds gravity so it floats upward, reaching equilibrium (F",
    ")을 이룹니다.": ") when the submerged volume fraction balances weight.",

    // ==================== 돌림힘과 역학적 평형 시뮬레이션 ====================
    "돌림힘과 역학적 평형 시뮬레이션 (2022 개정 고2 물리학)": "Torque & Mechanical Equilibrium Simulation",
    "돌림힘과 강체의 역학적 평형": "Torque & Rigid Body Mechanical Equilibrium",
    "1. 돌림힘 기초 & 벡터 분석": "1. Torque Basics & Vector Analysis",
    "2. 강체의 역학적 평형": "2. Rigid Body Mechanical Equilibrium",
    "회전 방향: 반시계 방향 +": "Rotation: Counter-Clockwise (+)",
    "알짜 돌림힘 τ = 20.0 N·m": "Net Torque τ = 20.0 N·m",
    "회전축-작용점 거리 r = ": "Pivot-Point Distance r = ",
    "작용 힘 F = ": "Applied Force F = ",
    "팔의 길이 d = ": "Lever Arm d = ",
    "돌림힘 τ = ": "Torque τ = ",
    "캔버스 위의 힘 화살표 끝 또는 작용점 P를 직접 드래그하여 거리 r 및 힘의 각도 θ를 조절할 수 있습니다.": "Drag the force arrow tip or action point P directly on the canvas to adjust distance r and angle θ.",
    "돌림힘 변수 조절": "Torque Variable Control",
    "회전축과의 거리 r": "Distance from Pivot r",
    "작용하는 힘의 크기 F": "Applied Force Magnitude F",
    "힘의 작용 각도 θ": "Force Angle θ",
    "교과 과정 주요 예제": "Curriculum Examples",
    "수직 작용 힘 90°": "Perpendicular Force 90°",
    "축 방향 힘 0°, τ=0": "Axial Force 0°, τ=0",
    "대각선 작용 45°": "Diagonal Force 45°",
    "둔각 작용 135°": "Obtuse Force 135°",
    "2022 개정 물리학 돌림힘 공식": "Torque Formula Breakdown",
    "팔의 길이 d = r · sinθ = ": "Lever arm d = r · sinθ = ",
    "역학적 평형 상태 ∑F=0, ∑τ=0": "Mechanical Equilibrium ∑F=0, ∑τ=0",
    "알짜 돌림힘: 0.0 N·m": "Net Torque: 0.0 N·m",
    "팔레트의 추를 클릭하여 막대 중앙에 즉시 추가하거나, 드래그하여 원하는 위치에 놓아보세요!": "Click weights in the palette to add them to the center, or drag them to any position!",
    "질량 추 배치": "Mass Placement",
    "모든 추 제거": "Clear All Weights",
    "받침대 1개 모드": "Single Support Mode",
    "받침대 2개 모드": "Dual Support Mode",
    "받침대 1개 (시소) 모드": "Single Support (Seesaw) Mode",
    "막대 & 받침점 설정": "Beam & Support Settings",
    "막대 자체 질량 M_beam": "Beam Mass M_beam",
    "받침점 A 위치 x_A": "Support A Position x_A",
    "받침점 B 위치 x_B": "Support B Position x_B",
    "역학적 평형 방정식 분석": "Mechanical Equilibrium Equations",
    "1) 병진 운동 평형 ∑F_y = 0": "1) Translational Equilibrium ∑F_y = 0",
    "F_N1 + F_N2 = M_beam + ∑m × g = ": "F_N1 + F_N2 = M_beam + ∑m × g = ",
    "2) 회전 운동 평형 ∑τ = 0": "2) Rotational Equilibrium ∑τ = 0",
    "반시계 돌림힘 = ": "CCW Torque = ",
    "시계 돌림힘 = ": "CW Torque = ",
    "알짜 돌림힘 ∑τ = ": "Net Torque ∑τ = ",
    "3) 받침점 수직항력 계산": "3) Support Normal Force Calculation",
    "받침점 A 수직항력 F_N1 = ": "Support A Normal Force F_N1 = ",
    "받침점 B 수직항력 F_N2 = ": "Support B Normal Force F_N2 = ",

    // Theory Modal
    "2022 개정 물리학 돌림힘과 강체의 역학적 평형": "Torque & Rigid Body Mechanical Equilibrium Concepts",
    "1. 돌림힘 \\vec{\\tau} 정의와 크기": "1. Definition & Magnitude of Torque \\vec{\\tau}",
    "1. 돌림힘 𝜏⃗ 정의와 크기": "1. Definition & Magnitude of Torque 𝜏⃗",
    "물체를 특정 회전축을 중심으로 회전시키려는 힘의 작용 물리량입니다.": "A physical quantity representing the tendency of a force to rotate an object around a specific axis.",
    "r: 회전축에서 힘의 작용점까지의 거리를 나타내는 위치 벡터": "r: Position vector from axis of rotation to point of application",
    "F: 작용점에 가해지는 힘의 크기 N": "F: Magnitude of force applied at action point (N)",
    "d = r · sinθ: 회전축에서 힘의 작용선까지의 수직 거리 팔의 길이": "d = r · sinθ: Perpendicular distance from rotation axis to line of action (lever arm)",
    "2. 돌림힘 부호 규약": "2. Torque Sign Convention",
    "반시계 방향 회전: 양의 값 +": "Counter-clockwise rotation: Positive (+)",
    "시계 방향 회전: 음의 값 -": "Clockwise rotation: Negative (-)",
    "힘이 회전축을 직접 지나가는 경우 θ = 0° 또는 180°, 팔의 길이 d = 0이 되어 돌림힘은 0이 됩니다.": "If the force line passes through the axis (θ = 0° or 180°), lever arm d = 0, so torque becomes 0.",
    "3. 강체의 역학적 평형 조건": "3. Conditions for Rigid Body Equilibrium",
    "강체가 회전하지 않고 정지해 있거나 등속 운동을 하기 위한 필수적 두 가지 조건:": "Two essential conditions for a rigid body to remain stationary or in uniform motion without rotation:",
    "1) 병진 운동 평형 알짜 힘 = 0: ∑F = 0 연직 방향 위쪽 힘 = 아래쪽 힘": "1) Translational equilibrium (Net force = 0): ∑F = 0 (Upward forces = Downward forces)",
    "2) 회전 운동 평형 알짜 돌림힘 = 0: ∑τ = 0 임의의 회전축 기준 시계 방향 돌림힘의 합 = 반시계 방향 돌림힘의 합": "2) Rotational equilibrium (Net torque = 0): ∑τ = 0 (Sum of CW torques = Sum of CCW torques around any pivot)",
    "4. 고2 물리학 문제 해결 팁": "4. Problem Solving Tips",
    "받침대가 2개 A, B인 막대 문제에서는 어느 한 받침대를 임의의 회전축으로 설정하면, 해당 받침점에서의 수직항력 F_NA에 의한 돌림힘이 0이 되므로 다른 받침점 B의 수직항력 F_NB를 쉽게 계산할 수 있습니다.": "In 2-support beam problems, setting one support as pivot makes its normal force torque 0, easily solving for the normal force at the second support.",
    
    // Node splitting exact matches for Torque Simulation
    "병진 운동 평형 ∑F_y = 0": "Translational Equilibrium ∑F_y = 0",
    "회전 운동 평형 ∑τ = 0": "Rotational Equilibrium ∑τ = 0",
    "받침점 수직항력 계산": "Support Normal Force Calculation",
    "1. 돌림힘 (Torque τ) 정의와 크기": "1. Definition & Magnitude of Torque (τ)",
    "공식": "Formula",
    ": 회전축에서 힘의 작용점까지의 거리를 나타내는 위치 벡터": ": Position vector from axis of rotation to point of application",
    ": 작용점에 가해지는 힘의 크기 N": ": Magnitude of force applied at action point (N)",
    ": 회전축에서 힘의 작용선까지의 수직 거리 팔의 길이": ": Perpendicular distance from rotation axis to line of action (lever arm)",
    "반시계 방향 회전": "Counter-clockwise rotation",
    ": 양의 값 ": ": Positive ",
    "시계 방향 회전": "Clockwise rotation",
    ": 음의 값 ": ": Negative ",
    "병진 운동 평형 알짜 힘 = 0": "Translational equilibrium (Net force = 0)",
    " 연직 방향 위쪽 힘 = 아래쪽 힘": " (Upward forces = Downward forces)",
    "회전 운동 평형 알짜 돌림힘 = 0": "Rotational equilibrium (Net torque = 0)",
    " 임의의 회전축 기준 시계 방향 돌림힘의 합 = 반시계 방향 돌림힘의 합": " (Sum of CW torques = Sum of CCW torques around any pivot)"
  };

  // Pre-sort dictionary keys by length in descending order to prevent partial word corruption
  let sortedKeys = null;
  function getSortedKeys() {
    if (!sortedKeys) {
      sortedKeys = Object.keys(dictionary).sort((a, b) => b.length - a.length);
    }
    return sortedKeys;
  }

  // Cache map to prevent O(N) loops on 60FPS canvas fillText calls
  const translationCache = new Map();

  // Function to translate a single text value
  function translateText(text) {
    if (!text) return null;
    if (translationCache.has(text)) {
      return translationCache.get(text);
    }

    let result = null;
    const trimmed = text.trim();
    if (dictionary[trimmed]) {
      result = text.replace(trimmed, dictionary[trimmed]);
    } else {
      let currentText = text;
      let modified = false;
      const keys = getSortedKeys();
      for (let i = 0; i < keys.length; i++) {
        const key = keys[i];
        if (currentText.includes(key)) {
          currentText = currentText.replaceAll(key, dictionary[key]);
          modified = true;
        }
      }
      if (modified) {
        result = currentText;
      }
    }

    if (result !== null) {
      translationCache.set(text, result);
    }
    return result;
  }

  // Walk DOM
  function walk(node) {
    if (node.nodeType === 3) { // Text node
      const translated = translateText(node.nodeValue);
      if (translated !== null) {
        node.nodeValue = translated;
      }
    } else if (node.nodeType === 1) { // Element node
      if (node.tagName !== 'SCRIPT' && node.tagName !== 'STYLE') {
        // Translate placeholders
        if (node.placeholder) {
          const trans = translateText(node.placeholder);
          if (trans) node.placeholder = trans;
        }
        // Translate button values or options
        if (node.tagName === 'INPUT' && (node.type === 'button' || node.type === 'submit') && node.value) {
          const trans = translateText(node.value);
          if (trans) node.value = trans;
        }
        
        node.childNodes.forEach(walk);
      }
    }
  }

  // Initial translation
  if (document.body) {
    walk(document.body);
  } else {
    document.addEventListener('DOMContentLoaded', () => walk(document.body));
  }

  if (document.title) {
    const trans = translateText(document.title);
    if (trans) document.title = trans;
  }

  // Real-time synchronization on language storage change
  window.addEventListener('storage', (e) => {
    if (e.key === 'sci-lab-lang') {
      window.location.reload();
    }
  });

  // MutationObserver to translate dynamic content
  const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      if (mutation.type === 'childList') {
        mutation.addedNodes.forEach(walk);
      } else if (mutation.type === 'characterData') {
        const node = mutation.target;
        const translated = translateText(node.nodeValue);
        if (translated !== null && node.nodeValue !== translated) {
          observer.disconnect();
          node.nodeValue = translated;
          observer.observe(document.body, { childList: true, characterData: true, subtree: true });
        }
      }
    });
  });

  if (document.body) {
    observer.observe(document.body, { childList: true, characterData: true, subtree: true });
  } else {
    document.addEventListener('DOMContentLoaded', () => {
      observer.observe(document.body, { childList: true, characterData: true, subtree: true });
    });
  }

  // Monkeypatch CanvasRenderingContext2D.prototype.fillText for canvas text translations
  if (window.CanvasRenderingContext2D) {
    const originalFillText = CanvasRenderingContext2D.prototype.fillText;
    CanvasRenderingContext2D.prototype.fillText = function(text, x, y, maxWidth) {
      if (typeof text === 'string') {
        const translated = translateText(text);
        if (translated !== null) {
          text = translated;
        }
      }
      if (maxWidth !== undefined) {
        return originalFillText.call(this, text, x, y, maxWidth);
      } else {
        return originalFillText.call(this, text, x, y);
      }
    };
  }
})();
